export const questions = [
  {
    qn: 1,
    question: "What is the capital of France?",
    a: "Berlin",
    b: "Madrid",
    c: "Paris",
    d: "Rome",
    co: "c",
  },
  {
    qn: 2,
    question: "Who wrote 'To Kill a Mockingbird'?",
    a: "Harper Lee",
    b: "Mark Twain",
    c: "Ernest Hemingway",
    d: "F. Scott Fitzgerald",
    co: "a",
  },
  {
    qn: 3,
    question: "What is the largest planet in our solar system?",
    a: "Earth",
    b: "Jupiter",
    c: "Saturn",
    d: "Mars",
    co: "b",
  },
  {
    qn: 4,
    question: "What is the smallest country in the world?",
    a: "Monaco",
    b: "Vatican City",
    c: "San Marino",
    d: "Liechtenstein",
    co: "b",
  },
  {
    qn: 5,
    question: "Who painted the Mona Lisa?",
    a: "Vincent van Gogh",
    b: "Pablo Picasso",
    c: "Leonardo da Vinci",
    d: "Claude Monet",
    co: "c",
  },
  {
    qn: 6,
    question: "What is the longest river in the world?",
    a: "Amazon River",
    b: "Nile River",
    c: "Yangtze River",
    d: "Mississippi River",
    co: "b",
  },
  {
    qn: 7,
    question: "Who discovered penicillin?",
    a: "Marie Curie",
    b: "Alexander Fleming",
    c: "Louis Pasteur",
    d: "Isaac Newton",
    co: "b",
  },
  {
    qn: 8,
    question: "What is the hardest natural substance on Earth?",
    a: "Gold",
    b: "Iron",
    c: "Diamond",
    d: "Platinum",
    co: "c",
  },
  {
    qn: 9,
    question: "What is the largest ocean on Earth?",
    a: "Atlantic Ocean",
    b: "Indian Ocean",
    c: "Arctic Ocean",
    d: "Pacific Ocean",
    co: "d",
  },
  {
    qn: 10,
    question: "Who was the first person to walk on the moon?",
    a: "Buzz Aldrin",
    b: "Yuri Gagarin",
    c: "Neil Armstrong",
    d: "Michael Collins",
    co: "c",
  },
  {
    qn: 11,
    question: "What is the chemical symbol for gold?",
    a: "Au",
    b: "Ag",
    c: "Pb",
    d: "Fe",
    co: "a",
  },
  {
    qn: 12,
    question: "Who wrote '1984'?",
    a: "George Orwell",
    b: "Aldous Huxley",
    c: "Ray Bradbury",
    d: "J.R.R. Tolkien",
    co: "a",
  },
  {
    qn: 13,
    question: "What is the capital of Japan?",
    a: "Seoul",
    b: "Beijing",
    c: "Tokyo",
    d: "Bangkok",
    co: "c",
  },
  {
    qn: 14,
    question: "What is the largest desert in the world?",
    a: "Sahara Desert",
    b: "Gobi Desert",
    c: "Kalahari Desert",
    d: "Arctic Desert",
    co: "a",
  },
  {
    qn: 15,
    question: "Who developed the theory of relativity?",
    a: "Isaac Newton",
    b: "Albert Einstein",
    c: "Galileo Galilei",
    d: "Nikola Tesla",
    co: "b",
  },
  {
    qn: 16,
    question: "What is the capital of Australia?",
    a: "Sydney",
    b: "Melbourne",
    c: "Canberra",
    d: "Brisbane",
    co: "c",
  },
  {
    qn: 17,
    question: "Who is known as the 'Father of Computers'?",
    a: "Alan Turing",
    b: "Charles Babbage",
    c: "John von Neumann",
    d: "Bill Gates",
    co: "b",
  },
  {
    qn: 18,
    question: "What is the tallest mountain in the world?",
    a: "K2",
    b: "Kangchenjunga",
    c: "Mount Everest",
    d: "Lhotse",
    co: "c",
  },
  {
    qn: 19,
    question: "Who wrote 'Pride and Prejudice'?",
    a: "Jane Austen",
    b: "Charlotte Bronte",
    c: "Emily Bronte",
    d: "Mary Shelley",
    co: "a",
  },
  {
    qn: 20,
    question: "What is the capital of Canada?",
    a: "Toronto",
    b: "Vancouver",
    c: "Ottawa",
    d: "Montreal",
    co: "c",
  },
  {
    qn: 21,
    question: "Who invented the telephone?",
    a: "Alexander Graham Bell",
    b: "Thomas Edison",
    c: "Nikola Tesla",
    d: "Guglielmo Marconi",
    co: "a",
  },
  {
    qn: 22,
    question: "What is the largest mammal in the world?",
    a: "Elephant",
    b: "Blue Whale",
    c: "Giraffe",
    d: "Hippopotamus",
    co: "b",
  },
  {
    qn: 23,
    question: "What is the capital of Italy?",
    a: "Venice",
    b: "Milan",
    c: "Rome",
    d: "Florence",
    co: "c",
  },
  {
    qn: 24,
    question: "Who wrote 'The Odyssey'?",
    a: "Homer",
    b: "Virgil",
    c: "Sophocles",
    d: "Euripides",
    co: "a",
  },
  {
    qn: 25,
    question: "What is the smallest planet in our solar system?",
    a: "Mercury",
    b: "Venus",
    c: "Mars",
    d: "Pluto",
    co: "a",
  },
  {
    qn: 26,
    question: "Who discovered America?",
    a: "Christopher Columbus",
    b: "Ferdinand Magellan",
    c: "Vasco da Gama",
    d: "James Cook",
    co: "a",
  },
  {
    qn: 27,
    question: "What is the capital of Russia?",
    a: "Saint Petersburg",
    b: "Moscow",
    c: "Kiev",
    d: "Minsk",
    co: "b",
  },
  {
    qn: 28,
    question: "Who wrote 'The Great Gatsby'?",
    a: "Ernest Hemingway",
    b: "F. Scott Fitzgerald",
    c: "John Steinbeck",
    d: "William Faulkner",
    co: "b",
  },
  {
    qn: 29,
    question: "What is the largest continent?",
    a: "Africa",
    b: "Asia",
    c: "Europe",
    d: "North America",
    co: "b",
  },
  {
    qn: 30,
    question: "Who was the first President of the United States?",
    a: "Thomas Jefferson",
    b: "John Adams",
    c: "George Washington",
    d: "James Madison",
    co: "c",
  },
  {
    qn: 31,
    question: "What is the capital of Germany?",
    a: "Munich",
    b: "Frankfurt",
    c: "Berlin",
    d: "Hamburg",
    co: "c",
  },
  {
    qn: 32,
    question: "Who wrote 'Moby-Dick'?",
    a: "Herman Melville",
    b: "Nathaniel Hawthorne",
    c: "Edgar Allan Poe",
    d: "Mark Twain",
    co: "a",
  },
  {
    qn: 33,
    question: "What is the largest island in the world?",
    a: "Greenland",
    b: "New Guinea",
    c: "Borneo",
    d: "Madagascar",
    co: "a",
  },
  {
    qn: 34,
    question: "Who invented the light bulb?",
    a: "Nikola Tesla",
    b: "Alexander Graham Bell",
    c: "Thomas Edison",
    d: "George Westinghouse",
    co: "c",
  },
  {
    qn: 35,
    question: "What is the capital of India?",
    a: "Mumbai",
    b: "New Delhi",
    c: "Bangalore",
    d: "Kolkata",
    co: "b",
  },
  {
    qn: 36,
    question: "Who wrote 'War and Peace'?",
    a: "Fyodor Dostoevsky",
    b: "Leo Tolstoy",
    c: "Anton Chekhov",
    d: "Ivan Turgenev",
    co: "b",
  },
  {
    qn: 37,
    question: "What is the largest bone in the human body?",
    a: "Femur",
    b: "Humerus",
    c: "Tibia",
    d: "Fibula",
    co: "a",
  },
  {
    qn: 38,
    question: "Who was the first woman to win a Nobel Prize?",
    a: "Marie Curie",
    b: "Rosalind Franklin",
    c: "Dorothy Hodgkin",
    d: "Ada Lovelace",
    co: "a",
  },
  {
    qn: 39,
    question: "What is the capital of Brazil?",
    a: "Rio de Janeiro",
    b: "São Paulo",
    c: "Brasília",
    d: "Salvador",
    co: "c",
  },
  {
    qn: 40,
    question: "Who wrote 'The Catcher in the Rye'?",
    a: "J.D. Salinger",
    b: "Harper Lee",
    c: "F. Scott Fitzgerald",
    d: "John Steinbeck",
    co: "a",
  },
  {
    qn: 41,
    question: "What is the largest organ in the human body?",
    a: "Heart",
    b: "Liver",
    c: "Skin",
    d: "Lungs",
    co: "c",
  },
  {
    qn: 42,
    question: "Who was the first woman to fly solo across the Atlantic Ocean?",
    a: "Amelia Earhart",
    b: "Bessie Coleman",
    c: "Harriet Quimby",
    d: "Jacqueline Cochran",
    co: "a",
  },
  {
    qn: 43,
    question: "What is the capital of Egypt?",
    a: "Cairo",
    b: "Alexandria",
    c: "Giza",
    d: "Luxor",
    co: "a",
  },
  {
    qn: 44,
    question: "Who wrote 'The Divine Comedy'?",
    a: "Geoffrey Chaucer",
    b: "Dante Alighieri",
    c: "John Milton",
    d: "Homer",
    co: "b",
  },
  {
    qn: 45,
    question: "What is the smallest bone in the human body?",
    a: "Stapes",
    b: "Incus",
    c: "Malleus",
    d: "Hyoid",
    co: "a",
  },
  {
    qn: 46,
    question: "Who was the first President of South Africa?",
    a: "Nelson Mandela",
    b: "F.W. de Klerk",
    c: "Thabo Mbeki",
    d: "Jacob Zuma",
    co: "a",
  },
  {
    qn: 47,
    question: "What is the capital of Argentina?",
    a: "Buenos Aires",
    b: "Córdoba",
    c: "Rosario",
    d: "Mendoza",
    co: "a",
  },
  {
    qn: 48,
    question: "Who wrote 'The Iliad'?",
    a: "Homer",
    b: "Virgil",
    c: "Sophocles",
    d: "Euripides",
    co: "a",
  },
  {
    qn: 49,
    question: "What is the largest muscle in the human body?",
    a: "Biceps",
    b: "Quadriceps",
    c: "Gluteus Maximus",
    d: "Trapezius",
    co: "c",
  },
  {
    qn: 50,
    question:
      "Who was the first woman to win a Nobel Prize in two different fields?",
    a: "Marie Curie",
    b: "Rosalind Franklin",
    c: "Dorothy Hodgkin",
    d: "Ada Lovelace",
    co: "a",
  },
  {
    qn: 51,
    question: "What is the capital of South Korea?",
    a: "Seoul",
    b: "Tokyo",
    c: "Beijing",
    d: "Bangkok",
    co: "a",
  },
  {
    qn: 52,
    question: "Who wrote 'The Hobbit'?",
    a: "J.R.R. Tolkien",
    b: "C.S. Lewis",
    c: "George R.R. Martin",
    d: "J.K. Rowling",
    co: "a",
  },
  {
    qn: 53,
    question: "What is the chemical symbol for water?",
    a: "H2O",
    b: "O2",
    c: "CO2",
    d: "NaCl",
    co: "a",
  },
  {
    qn: 54,
    question: "Who was the first man in space?",
    a: "Neil Armstrong",
    b: "Yuri Gagarin",
    c: "Buzz Aldrin",
    d: "John Glenn",
    co: "b",
  },
  {
    qn: 55,
    question: "What is the capital of Mexico?",
    a: "Guadalajara",
    b: "Monterrey",
    c: "Mexico City",
    d: "Cancun",
    co: "c",
  },
  {
    qn: 56,
    question: "Who wrote 'The Picture of Dorian Gray'?",
    a: "Oscar Wilde",
    b: "Charles Dickens",
    c: "Mark Twain",
    d: "H.G. Wells",
    co: "a",
  },
  {
    qn: 57,
    question: "What is the largest country by area?",
    a: "Canada",
    b: "China",
    c: "United States",
    d: "Russia",
    co: "d",
  },
  {
    qn: 58,
    question: "Who discovered the law of gravity?",
    a: "Albert Einstein",
    b: "Isaac Newton",
    c: "Galileo Galilei",
    d: "Nikola Tesla",
    co: "b",
  },
  {
    qn: 59,
    question: "What is the capital of Spain?",
    a: "Barcelona",
    b: "Madrid",
    c: "Seville",
    d: "Valencia",
    co: "b",
  },
  {
    qn: 60,
    question: "Who wrote 'The Adventures of Tom Sawyer'?",
    a: "Mark Twain",
    b: "Ernest Hemingway",
    c: "F. Scott Fitzgerald",
    d: "John Steinbeck",
    co: "a",
  },
  {
    qn: 61,
    question: "What is the smallest ocean in the world?",
    a: "Atlantic Ocean",
    b: "Indian Ocean",
    c: "Arctic Ocean",
    d: "Southern Ocean",
    co: "c",
  },
  {
    qn: 62,
    question: "Who painted the Sistine Chapel ceiling?",
    a: "Leonardo da Vinci",
    b: "Michelangelo",
    c: "Raphael",
    d: "Donatello",
    co: "b",
  },
  {
    qn: 63,
    question: "What is the capital of China?",
    a: "Shanghai",
    b: "Beijing",
    c: "Hong Kong",
    d: "Guangzhou",
    co: "b",
  },
  {
    qn: 64,
    question: "Who wrote 'The Brothers Karamazov'?",
    a: "Leo Tolstoy",
    b: "Fyodor Dostoevsky",
    c: "Anton Chekhov",
    d: "Ivan Turgenev",
    co: "b",
  },
  {
    qn: 65,
    question: "What is the largest lake in the world?",
    a: "Lake Superior",
    b: "Lake Victoria",
    c: "Caspian Sea",
    d: "Lake Baikal",
    co: "c",
  },
  {
    qn: 66,
    question: "Who discovered the structure of DNA?",
    a: "James Watson and Francis Crick",
    b: "Marie Curie",
    c: "Gregor Mendel",
    d: "Rosalind Franklin",
    co: "a",
  },
  {
    qn: 67,
    question: "What is the capital of Greece?",
    a: "Athens",
    b: "Thessaloniki",
    c: "Patras",
    d: "Heraklion",
    co: "a",
  },
  {
    qn: 68,
    question: "Who wrote 'The Count of Monte Cristo'?",
    a: "Victor Hugo",
    b: "Alexandre Dumas",
    c: "Jules Verne",
    d: "Honoré de Balzac",
    co: "b",
  },
  {
    qn: 69,
    question: "What is the largest island in the Mediterranean Sea?",
    a: "Sicily",
    b: "Sardinia",
    c: "Cyprus",
    d: "Crete",
    co: "a",
  },
  {
    qn: 70,
    question: "Who developed the polio vaccine?",
    a: "Albert Sabin",
    b: "Louis Pasteur",
    c: "Jonas Salk",
    d: "Edward Jenner",
    co: "c",
  },
  {
    qn: 71,
    question: "What is the capital of Turkey?",
    a: "Istanbul",
    b: "Ankara",
    c: "Izmir",
    d: "Antalya",
    co: "b",
  },
  {
    qn: 72,
    question: "Who wrote 'The Old Man and the Sea'?",
    a: "Ernest Hemingway",
    b: "F. Scott Fitzgerald",
    c: "John Steinbeck",
    d: "William Faulkner",
    co: "a",
  },
  {
    qn: 73,
    question: "What is the largest desert in Africa?",
    a: "Kalahari Desert",
    b: "Sahara Desert",
    c: "Namib Desert",
    d: "Libyan Desert",
    co: "b",
  },
  {
    qn: 74,
    question: "Who discovered the electron?",
    a: "Niels Bohr",
    b: "Ernest Rutherford",
    c: "J.J. Thomson",
    d: "James Chadwick",
    co: "c",
  },
  {
    qn: 75,
    question: "What is the capital of Portugal?",
    a: "Lisbon",
    b: "Porto",
    c: "Braga",
    d: "Coimbra",
    co: "a",
  },
  {
    qn: 76,
    question: "Who wrote 'The Scarlet Letter'?",
    a: "Nathaniel Hawthorne",
    b: "Herman Melville",
    c: "Edgar Allan Poe",
    d: "Mark Twain",
    co: "a",
  },
  {
    qn: 77,
    question: "What is the largest river in Africa?",
    a: "Congo River",
    b: "Niger River",
    c: "Nile River",
    d: "Zambezi River",
    co: "c",
  },
  {
    qn: 78,
    question: "Who discovered radioactivity?",
    a: "Marie Curie",
    b: "Henri Becquerel",
    c: "Ernest Rutherford",
    d: "Wilhelm Röntgen",
    co: "b",
  },
  {
    qn: 79,
    question: "What is the capital of Thailand?",
    a: "Bangkok",
    b: "Phuket",
    c: "Chiang Mai",
    d: "Pattaya",
    co: "a",
  },
  {
    qn: 80,
    question: "Who wrote 'The Canterbury Tales'?",
    a: "Geoffrey Chaucer",
    b: "William Shakespeare",
    c: "John Milton",
    d: "Christopher Marlowe",
    co: "a",
  },
  {
    qn: 81,
    question: "What is the largest volcano in the world?",
    a: "Mount Vesuvius",
    b: "Mount St. Helens",
    c: "Mauna Loa",
    d: "Mount Fuji",
    co: "c",
  },
  {
    qn: 82,
    question: "Who was the first woman to win a Nobel Prize in Literature?",
    a: "Selma Lagerlöf",
    b: "Toni Morrison",
    c: "Gabriela Mistral",
    d: "Pearl S. Buck",
    co: "a",
  },
  {
    qn: 83,
    question: "What is the capital of Saudi Arabia?",
    a: "Jeddah",
    b: "Mecca",
    c: "Riyadh",
    d: "Medina",
    co: "c",
  },
  {
    qn: 84,
    question: "Who wrote 'The Metamorphosis'?",
    a: "Franz Kafka",
    b: "Albert Camus",
    c: "Jean-Paul Sartre",
    d: "Hermann Hesse",
    co: "a",
  },
  {
    qn: 85,
    question: "What is the largest coral reef system in the world?",
    a: "Great Barrier Reef",
    b: "Belize Barrier Reef",
    c: "Red Sea Coral Reef",
    d: "New Caledonia Barrier Reef",
    co: "a",
  },
  {
    qn: 86,
    question: "Who discovered the circulation of blood?",
    a: "Andreas Vesalius",
    b: "William Harvey",
    c: "Hippocrates",
    d: "Galen",
    co: "b",
  },
  {
    qn: 87,
    question: "What is the capital of Sweden?",
    a: "Gothenburg",
    b: "Malmö",
    c: "Stockholm",
    d: "Uppsala",
    co: "c",
  },
  {
    qn: 88,
    question: "Who wrote 'The Three Musketeers'?",
    a: "Victor Hugo",
    b: "Alexandre Dumas",
    c: "Jules Verne",
    d: "Honoré de Balzac",
    co: "b",
  },
  {
    qn: 89,
    question: "What is the largest desert in Asia?",
    a: "Gobi Desert",
    b: "Arabian Desert",
    c: "Karakum Desert",
    d: "Thar Desert",
    co: "a",
  },
  {
    qn: 90,
    question: "Who developed the theory of evolution?",
    a: "Gregor Mendel",
    b: "Charles Darwin",
    c: "Alfred Russel Wallace",
    d: "Jean-Baptiste Lamarck",
    co: "b",
  },
  {
    qn: 91,
    question: "What is the capital of Norway?",
    a: "Bergen",
    b: "Trondheim",
    c: "Oslo",
    d: "Stavanger",
    co: "c",
  },
  {
    qn: 92,
    question: "Who wrote 'Crime and Punishment'?",
    a: "Leo Tolstoy",
    b: "Fyodor Dostoevsky",
    c: "Anton Chekhov",
    d: "Ivan Turgenev",
    co: "b",
  },
  {
    qn: 93,
    question: "What is the largest rainforest in the world?",
    a: "Congo Rainforest",
    b: "Amazon Rainforest",
    c: "Daintree Rainforest",
    d: "Southeast Asian Rainforest",
    co: "b",
  },
  {
    qn: 94,
    question: "Who discovered the neutron?",
    a: "Niels Bohr",
    b: "Ernest Rutherford",
    c: "J.J. Thomson",
    d: "James Chadwick",
    co: "d",
  },
  {
    qn: 95,
    question: "What is the capital of the Netherlands?",
    a: "Rotterdam",
    b: "The Hague",
    c: "Amsterdam",
    d: "Utrecht",
    co: "c",
  },
  {
    qn: 96,
    question: "Who wrote 'The Grapes of Wrath'?",
    a: "Ernest Hemingway",
    b: "F. Scott Fitzgerald",
    c: "John Steinbeck",
    d: "William Faulkner",
    co: "c",
  },
  {
    qn: 97,
    question: "What is the largest island in the Caribbean?",
    a: "Cuba",
    b: "Hispaniola",
    c: "Jamaica",
    d: "Puerto Rico",
    co: "a",
  },
  {
    qn: 98,
    question: "Who discovered the proton?",
    a: "Niels Bohr",
    b: "Ernest Rutherford",
    c: "J.J. Thomson",
    d: "James Chadwick",
    co: "b",
  },
  {
    qn: 99,
    question: "What is the capital of Switzerland?",
    a: "Zurich",
    b: "Geneva",
    c: "Bern",
    d: "Basel",
    co: "c",
  },
  {
    qn: 100,
    question: "Who wrote 'Brave New World'?",
    a: "George Orwell",
    b: "Aldous Huxley",
    c: "Ray Bradbury",
    d: "J.R.R. Tolkien",
    co: "b",
  },
  {
    qn: 101,
    question: "What is the capital of South Africa?",
    a: "Johannesburg",
    b: "Pretoria",
    c: "Cape Town",
    d: "Durban",
    co: "b",
  },
  {
    qn: 102,
    question: "Who wrote 'The Road Not Taken'?",
    a: "Robert Frost",
    b: "Walt Whitman",
    c: "Emily Dickinson",
    d: "Sylvia Plath",
    co: "a",
  },
  {
    qn: 103,
    question: "What is the largest moon of Saturn?",
    a: "Europa",
    b: "Titan",
    c: "Ganymede",
    d: "Callisto",
    co: "b",
  },
  {
    qn: 104,
    question: "Who discovered the electron?",
    a: "Niels Bohr",
    b: "Ernest Rutherford",
    c: "J.J. Thomson",
    d: "James Chadwick",
    co: "c",
  },
  {
    qn: 105,
    question: "What is the capital of New Zealand?",
    a: "Auckland",
    b: "Wellington",
    c: "Christchurch",
    d: "Hamilton",
    co: "b",
  },
  {
    qn: 106,
    question: "Who wrote 'The Catch-22'?",
    a: "Joseph Heller",
    b: "Kurt Vonnegut",
    c: "George Orwell",
    d: "Aldous Huxley",
    co: "a",
  },
  {
    qn: 107,
    question: "What is the largest island in the Mediterranean Sea?",
    a: "Sicily",
    b: "Sardinia",
    c: "Cyprus",
    d: "Crete",
    co: "a",
  },
  {
    qn: 108,
    question: "Who developed the theory of general relativity?",
    a: "Isaac Newton",
    b: "Albert Einstein",
    c: "Galileo Galilei",
    d: "Nikola Tesla",
    co: "b",
  },
  {
    qn: 109,
    question: "What is the capital of Finland?",
    a: "Helsinki",
    b: "Oslo",
    c: "Stockholm",
    d: "Copenhagen",
    co: "a",
  },
  {
    qn: 110,
    question: "Who wrote 'The Sun Also Rises'?",
    a: "Ernest Hemingway",
    b: "F. Scott Fitzgerald",
    c: "John Steinbeck",
    d: "William Faulkner",
    co: "a",
  },
  {
    qn: 111,
    question: "What is the largest ocean on Earth?",
    a: "Atlantic Ocean",
    b: "Indian Ocean",
    c: "Arctic Ocean",
    d: "Pacific Ocean",
    co: "d",
  },
  {
    qn: 112,
    question: "Who discovered the law of gravity?",
    a: "Albert Einstein",
    b: "Isaac Newton",
    c: "Galileo Galilei",
    d: "Nikola Tesla",
    co: "b",
  },
  {
    qn: 113,
    question: "What is the capital of Denmark?",
    a: "Copenhagen",
    b: "Oslo",
    c: "Stockholm",
    d: "Helsinki",
    co: "a",
  },
  {
    qn: 114,
    question: "Who wrote 'The Great Gatsby'?",
    a: "Ernest Hemingway",
    b: "F. Scott Fitzgerald",
    c: "John Steinbeck",
    d: "William Faulkner",
    co: "b",
  },
  {
    qn: 115,
    question: "What is the largest desert in the world?",
    a: "Sahara Desert",
    b: "Gobi Desert",
    c: "Kalahari Desert",
    d: "Arctic Desert",
    co: "a",
  },
  {
    qn: 116,
    question: "Who developed the theory of evolution?",
    a: "Gregor Mendel",
    b: "Charles Darwin",
    c: "Alfred Russel Wallace",
    d: "Jean-Baptiste Lamarck",
    co: "b",
  },
  {
    qn: 117,
    question: "What is the capital of Norway?",
    a: "Bergen",
    b: "Trondheim",
    c: "Oslo",
    d: "Stavanger",
    co: "c",
  },
  {
    qn: 118,
    question: "Who wrote 'Crime and Punishment'?",
    a: "Leo Tolstoy",
    b: "Fyodor Dostoevsky",
    c: "Anton Chekhov",
    d: "Ivan Turgenev",
    co: "b",
  },
  {
    qn: 119,
    question: "What is the largest rainforest in the world?",
    a: "Congo Rainforest",
    b: "Amazon Rainforest",
    c: "Daintree Rainforest",
    d: "Southeast Asian Rainforest",
    co: "b",
  },
  {
    qn: 120,
    question: "Who discovered the neutron?",
    a: "Niels Bohr",
    b: "Ernest Rutherford",
    c: "J.J. Thomson",
    d: "James Chadwick",
    co: "d",
  },
  {
    qn: 121,
    question: "What is the capital of the Netherlands?",
    a: "Rotterdam",
    b: "The Hague",
    c: "Amsterdam",
    d: "Utrecht",
    co: "c",
  },
  {
    qn: 122,
    question: "Who wrote 'The Grapes of Wrath'?",
    a: "Ernest Hemingway",
    b: "F. Scott Fitzgerald",
    c: "John Steinbeck",
    d: "William Faulkner",
    co: "c",
  },
  {
    qn: 123,
    question: "What is the largest island in the Caribbean?",
    a: "Cuba",
    b: "Hispaniola",
    c: "Jamaica",
    d: "Puerto Rico",
    co: "a",
  },
  {
    qn: 124,
    question: "Who discovered the proton?",
    a: "Niels Bohr",
    b: "Ernest Rutherford",
    c: "J.J. Thomson",
    d: "James Chadwick",
    co: "b",
  },
  {
    qn: 125,
    question: "What is the capital of Switzerland?",
    a: "Zurich",
    b: "Geneva",
    c: "Bern",
    d: "Basel",
    co: "c",
  },
  {
    qn: 126,
    question: "Who wrote 'Brave New World'?",
    a: "George Orwell",
    b: "Aldous Huxley",
    c: "Ray Bradbury",
    d: "J.R.R. Tolkien",
    co: "b",
  },
  {
    qn: 127,
    question: "What is the capital of South Korea?",
    a: "Seoul",
    b: "Tokyo",
    c: "Beijing",
    d: "Bangkok",
    co: "a",
  },
  {
    qn: 128,
    question: "Who wrote 'The Hobbit'?",
    a: "J.R.R. Tolkien",
    b: "C.S. Lewis",
    c: "George R.R. Martin",
    d: "J.K. Rowling",
    co: "a",
  },
  {
    qn: 129,
    question: "What is the chemical symbol for water?",
    a: "H2O",
    b: "O2",
    c: "CO2",
    d: "NaCl",
    co: "a",
  },
  {
    qn: 130,
    question: "Who was the first man in space?",
    a: "Neil Armstrong",
    b: "Yuri Gagarin",
    c: "Buzz Aldrin",
    d: "John Glenn",
    co: "b",
  },
  {
    qn: 131,
    question: "What is the capital of Mexico?",
    a: "Guadalajara",
    b: "Monterrey",
    c: "Mexico City",
    d: "Cancun",
    co: "c",
  },
  {
    qn: 132,
    question: "Who wrote 'The Picture of Dorian Gray'?",
    a: "Oscar Wilde",
    b: "Charles Dickens",
    c: "Mark Twain",
    d: "H.G. Wells",
    co: "a",
  },
  {
    qn: 133,
    question: "What is the largest country by area?",
    a: "Canada",
    b: "China",
    c: "United States",
    d: "Russia",
    co: "d",
  },
  {
    qn: 134,
    question: "Who discovered the law of gravity?",
    a: "Albert Einstein",
    b: "Isaac Newton",
    c: "Galileo Galilei",
    d: "Nikola Tesla",
    co: "b",
  },
  {
    qn: 135,
    question: "What is the capital of Spain?",
    a: "Barcelona",
    b: "Madrid",
    c: "Seville",
    d: "Valencia",
    co: "b",
  },
  {
    qn: 136,
    question: "Who wrote 'The Adventures of Tom Sawyer'?",
    a: "Mark Twain",
    b: "Ernest Hemingway",
    c: "F. Scott Fitzgerald",
    d: "John Steinbeck",
    co: "a",
  },
  {
    qn: 137,
    question: "What is the smallest ocean in the world?",
    a: "Atlantic Ocean",
    b: "Indian Ocean",
    c: "Arctic Ocean",
    d: "Southern Ocean",
    co: "c",
  },
  {
    qn: 138,
    question: "Who painted the Sistine Chapel ceiling?",
    a: "Leonardo da Vinci",
    b: "Michelangelo",
    c: "Raphael",
    d: "Donatello",
    co: "b",
  },
  {
    qn: 139,
    question: "What is the capital of China?",
    a: "Shanghai",
    b: "Beijing",
    c: "Hong Kong",
    d: "Guangzhou",
    co: "b",
  },
  {
    qn: 140,
    question: "Who wrote 'The Brothers Karamazov'?",
    a: "Leo Tolstoy",
    b: "Fyodor Dostoevsky",
    c: "Anton Chekhov",
    d: "Ivan Turgenev",
    co: "b",
  },
  {
    qn: 141,
    question: "What is the largest lake in the world?",
    a: "Lake Superior",
    b: "Lake Victoria",
    c: "Caspian Sea",
    d: "Lake Baikal",
    co: "c",
  },
  {
    qn: 142,
    question: "Who discovered the structure of DNA?",
    a: "James Watson and Francis Crick",
    b: "Marie Curie",
    c: "Gregor Mendel",
    d: "Rosalind Franklin",
    co: "a",
  },
  {
    qn: 143,
    question: "What is the capital of Greece?",
    a: "Athens",
    b: "Thessaloniki",
    c: "Patras",
    d: "Heraklion",
    co: "a",
  },
  {
    qn: 144,
    question: "Who wrote 'The Count of Monte Cristo'?",
    a: "Victor Hugo",
    b: "Alexandre Dumas",
    c: "Jules Verne",
    d: "Honoré de Balzac",
    co: "b",
  },
  {
    qn: 145,
    question: "What is the largest island in the Mediterranean Sea?",
    a: "Sicily",
    b: "Sardinia",
    c: "Cyprus",
    d: "Crete",
    co: "a",
  },
  {
    qn: 146,
    question: "Who developed the polio vaccine?",
    a: "Albert Sabin",
    b: "Louis Pasteur",
    c: "Jonas Salk",
    d: "Edward Jenner",
    co: "c",
  },
  {
    qn: 147,
    question: "What is the capital of Turkey?",
    a: "Istanbul",
    b: "Ankara",
    c: "Izmir",
    d: "Antalya",
    co: "b",
  },
  {
    qn: 148,
    question: "Who wrote 'The Old Man and the Sea'?",
    a: "Ernest Hemingway",
    b: "F. Scott Fitzgerald",
    c: "John Steinbeck",
    d: "William Faulkner",
    co: "a",
  },
  {
    qn: 149,
    question: "What is the largest desert in Africa?",
    a: "Kalahari Desert",
    b: "Sahara Desert",
    c: "Namib Desert",
    d: "Libyan Desert",
    co: "b",
  },
  {
    qn: 150,
    question: "Who discovered the electron?",
    a: "Niels Bohr",
    b: "Ernest Rutherford",
    c: "J.J. Thomson",
    d: "James Chadwick",
    co: "c",
  },
  {
    qn: 151,
    question: "What is the capital of Poland?",
    a: "Warsaw",
    b: "Krakow",
    c: "Gdansk",
    d: "Wroclaw",
    co: "a",
  },
  {
    qn: 152,
    question: "Who wrote 'The Jungle Book'?",
    a: "Rudyard Kipling",
    b: "Jules Verne",
    c: "H.G. Wells",
    d: "Mark Twain",
    co: "a",
  },
  {
    qn: 153,
    question: "What is the largest planet in our solar system?",
    a: "Earth",
    b: "Jupiter",
    c: "Saturn",
    d: "Mars",
    co: "b",
  },
  {
    qn: 154,
    question: "Who painted 'Starry Night'?",
    a: "Vincent van Gogh",
    b: "Pablo Picasso",
    c: "Claude Monet",
    d: "Leonardo da Vinci",
    co: "a",
  },
  {
    qn: 155,
    question: "What is the capital of Norway?",
    a: "Bergen",
    b: "Trondheim",
    c: "Oslo",
    d: "Stavanger",
    co: "c",
  },
  {
    qn: 156,
    question: "Who wrote 'The Catcher in the Rye'?",
    a: "J.D. Salinger",
    b: "Harper Lee",
    c: "F. Scott Fitzgerald",
    d: "John Steinbeck",
    co: "a",
  },
  {
    qn: 157,
    question: "What is the largest ocean on Earth?",
    a: "Atlantic Ocean",
    b: "Indian Ocean",
    c: "Arctic Ocean",
    d: "Pacific Ocean",
    co: "d",
  },
  {
    qn: 158,
    question: "Who discovered penicillin?",
    a: "Marie Curie",
    b: "Alexander Fleming",
    c: "Louis Pasteur",
    d: "Isaac Newton",
    co: "b",
  },
  {
    qn: 159,
    question: "What is the capital of Japan?",
    a: "Seoul",
    b: "Beijing",
    c: "Tokyo",
    d: "Bangkok",
    co: "c",
  },
  {
    qn: 160,
    question: "Who wrote '1984'?",
    a: "George Orwell",
    b: "Aldous Huxley",
    c: "Ray Bradbury",
    d: "J.R.R. Tolkien",
    co: "a",
  },
  {
    qn: 161,
    question: "What is the smallest country in the world?",
    a: "Monaco",
    b: "Vatican City",
    c: "San Marino",
    d: "Liechtenstein",
    co: "b",
  },
  {
    qn: 162,
    question: "Who painted the Mona Lisa?",
    a: "Vincent van Gogh",
    b: "Pablo Picasso",
    c: "Leonardo da Vinci",
    d: "Claude Monet",
    co: "c",
  },
  {
    qn: 163,
    question: "What is the longest river in the world?",
    a: "Amazon River",
    b: "Nile River",
    c: "Yangtze River",
    d: "Mississippi River",
    co: "b",
  },
  {
    qn: 164,
    question: "Who discovered penicillin?",
    a: "Marie Curie",
    b: "Alexander Fleming",
    c: "Louis Pasteur",
    d: "Isaac Newton",
    co: "b",
  },
  {
    qn: 165,
    question: "What is the hardest natural substance on Earth?",
    a: "Gold",
    b: "Iron",
    c: "Diamond",
    d: "Platinum",
    co: "c",
  },
  {
    qn: 166,
    question: "What is the largest ocean on Earth?",
    a: "Atlantic Ocean",
    b: "Indian Ocean",
    c: "Arctic Ocean",
    d: "Pacific Ocean",
    co: "d",
  },
  {
    qn: 167,
    question: "Who was the first person to walk on the moon?",
    a: "Buzz Aldrin",
    b: "Yuri Gagarin",
    c: "Neil Armstrong",
    d: "Michael Collins",
    co: "c",
  },
  {
    qn: 168,
    question: "What is the chemical symbol for gold?",
    a: "Au",
    b: "Ag",
    c: "Pb",
    d: "Fe",
    co: "a",
  },
  {
    qn: 169,
    question: "Who wrote '1984'?",
    a: "George Orwell",
    b: "Aldous Huxley",
    c: "Ray Bradbury",
    d: "J.R.R. Tolkien",
    co: "a",
  },
  {
    qn: 170,
    question: "What is the capital of Japan?",
    a: "Seoul",
    b: "Beijing",
    c: "Tokyo",
    d: "Bangkok",
    co: "c",
  },
  {
    qn: 171,
    question: "What is the largest desert in the world?",
    a: "Sahara Desert",
    b: "Gobi Desert",
    c: "Kalahari Desert",
    d: "Arctic Desert",
    co: "a",
  },
  {
    qn: 172,
    question: "Who developed the theory of relativity?",
    a: "Isaac Newton",
    b: "Albert Einstein",
    c: "Galileo Galilei",
    d: "Nikola Tesla",
    co: "b",
  },
  {
    qn: 173,
    question: "What is the capital of Australia?",
    a: "Sydney",
    b: "Melbourne",
    c: "Canberra",
    d: "Brisbane",
    co: "c",
  },
  {
    qn: 174,
    question: "Who is known as the 'Father of Computers'?",
    a: "Alan Turing",
    b: "Charles Babbage",
    c: "John von Neumann",
    d: "Bill Gates",
    co: "b",
  },
  {
    qn: 175,
    question: "What is the tallest mountain in the world?",
    a: "K2",
    b: "Kangchenjunga",
    c: "Mount Everest",
    d: "Lhotse",
    co: "c",
  },
  {
    qn: 176,
    question: "Who wrote 'Pride and Prejudice'?",
    a: "Jane Austen",
    b: "Charlotte Bronte",
    c: "Emily Bronte",
    d: "Mary Shelley",
    co: "a",
  },
  {
    qn: 177,
    question: "What is the capital of Canada?",
    a: "Toronto",
    b: "Vancouver",
    c: "Ottawa",
    d: "Montreal",
    co: "c",
  },
  {
    qn: 178,
    question: "Who invented the telephone?",
    a: "Alexander Graham Bell",
    b: "Thomas Edison",
    c: "Nikola Tesla",
    d: "Guglielmo Marconi",
    co: "a",
  },
  {
    qn: 179,
    question: "What is the largest mammal in the world?",
    a: "Elephant",
    b: "Blue Whale",
    c: "Giraffe",
    d: "Hippopotamus",
    co: "b",
  },
  {
    qn: 180,
    question: "What is the capital of Italy?",
    a: "Venice",
    b: "Milan",
    c: "Rome",
    d: "Florence",
    co: "c",
  },
  {
    qn: 181,
    question: "Who wrote 'The Odyssey'?",
    a: "Homer",
    b: "Virgil",
    c: "Sophocles",
    d: "Euripides",
    co: "a",
  },
  {
    qn: 182,
    question: "What is the smallest planet in our solar system?",
    a: "Mercury",
    b: "Venus",
    c: "Mars",
    d: "Pluto",
    co: "a",
  },
  {
    qn: 183,
    question: "Who discovered America?",
    a: "Christopher Columbus",
    b: "Ferdinand Magellan",
    c: "Vasco da Gama",
    d: "James Cook",
    co: "a",
  },
  {
    qn: 184,
    question: "What is the capital of Russia?",
    a: "Saint Petersburg",
    b: "Moscow",
    c: "Kiev",
    d: "Minsk",
    co: "b",
  },
  {
    qn: 185,
    question: "Who wrote 'The Great Gatsby'?",
    a: "Ernest Hemingway",
    b: "F. Scott Fitzgerald",
    c: "John Steinbeck",
    d: "William Faulkner",
    co: "b",
  },
  {
    qn: 186,
    question: "What is the largest continent?",
    a: "Africa",
    b: "Asia",
    c: "Europe",
    d: "North America",
    co: "b",
  },
  {
    qn: 187,
    question: "Who was the first President of the United States?",
    a: "Thomas Jefferson",
    b: "John Adams",
    c: "George Washington",
    d: "James Madison",
    co: "c",
  },
  {
    qn: 188,
    question: "What is the capital of Germany?",
    a: "Munich",
    b: "Frankfurt",
    c: "Berlin",
    d: "Hamburg",
    co: "c",
  },
  {
    qn: 189,
    question: "Who wrote 'Moby-Dick'?",
    a: "Herman Melville",
    b: "Nathaniel Hawthorne",
    c: "Edgar Allan Poe",
    d: "Mark Twain",
    co: "a",
  },
  {
    qn: 190,
    question: "What is the largest island in the world?",
    a: "Greenland",
    b: "New Guinea",
    c: "Borneo",
    d: "Madagascar",
    co: "a",
  },
  {
    qn: 191,
    question: "Who invented the light bulb?",
    a: "Nikola Tesla",
    b: "Alexander Graham Bell",
    c: "Thomas Edison",
    d: "George Westinghouse",
    co: "c",
  },
  {
    qn: 192,
    question: "What is the capital of India?",
    a: "Mumbai",
    b: "New Delhi",
    c: "Bangalore",
    d: "Kolkata",
    co: "b",
  },
  {
    qn: 193,
    question: "Who wrote 'War and Peace'?",
    a: "Fyodor Dostoevsky",
    b: "Leo Tolstoy",
    c: "Anton Chekhov",
    d: "Ivan Turgenev",
    co: "b",
  },
  {
    qn: 194,
    question: "What is the largest bone in the human body?",
    a: "Femur",
    b: "Humerus",
    c: "Tibia",
    d: "Fibula",
    co: "a",
  },
  {
    qn: 195,
    question: "Who was the first woman to win a Nobel Prize?",
    a: "Marie Curie",
    b: "Rosalind Franklin",
    c: "Dorothy Hodgkin",
    d: "Ada Lovelace",
    co: "a",
  },
  {
    qn: 196,
    question: "What is the capital of Brazil?",
    a: "Rio de Janeiro",
    b: "São Paulo",
    c: "Brasília",
    d: "Salvador",
    co: "c",
  },
  {
    qn: 197,
    question: "Who wrote 'The Catcher in the Rye'?",
    a: "J.D. Salinger",
    b: "Harper Lee",
    c: "F. Scott Fitzgerald",
    d: "John Steinbeck",
    co: "a",
  },
  {
    qn: 198,
    question: "What is the largest organ in the human body?",
    a: "Heart",
    b: "Liver",
    c: "Skin",
    d: "Lungs",
    co: "c",
  },
  {
    qn: 199,
    question: "Who was the first woman to fly solo across the Atlantic Ocean?",
    a: "Amelia Earhart",
    b: "Bessie Coleman",
    c: "Harriet Quimby",
    d: "Jacqueline Cochran",
    co: "a",
  },
  {
    qn: 200,
    question: "What is the capital of Egypt?",
    a: "Cairo",
    b: "Alexandria",
    c: "Giza",
    d: "Luxor",
    co: "a",
  },
  {
    qn: 201,
    question: "What is the chemical symbol for sodium?",
    a: "Na",
    b: "S",
    c: "N",
    d: "Sa",
    co: "a",
  },
  {
    qn: 202,
    question: "Who proposed the law of universal gravitation?",
    a: "Albert Einstein",
    b: "Isaac Newton",
    c: "Galileo Galilei",
    d: "Johannes Kepler",
    co: "b",
  },
  {
    qn: 203,
    question: "What is the speed of light in a vacuum?",
    a: "300,000 km/s",
    b: "150,000 km/s",
    c: "450,000 km/s",
    d: "600,000 km/s",
    co: "a",
  },
  {
    qn: 204,
    question: "Who is known as the father of modern chemistry?",
    a: "Dmitri Mendeleev",
    b: "Antoine Lavoisier",
    c: "Robert Boyle",
    d: "John Dalton",
    co: "b",
  },
  {
    qn: 205,
    question: "What is the most abundant gas in the Earth's atmosphere?",
    a: "Oxygen",
    b: "Carbon Dioxide",
    c: "Nitrogen",
    d: "Hydrogen",
    co: "c",
  },
  {
    qn: 206,
    question: "Who developed the first successful polio vaccine?",
    a: "Albert Sabin",
    b: "Louis Pasteur",
    c: "Jonas Salk",
    d: "Edward Jenner",
    co: "c",
  },
  {
    qn: 207,
    question: "What is the powerhouse of the cell?",
    a: "Nucleus",
    b: "Ribosome",
    c: "Mitochondria",
    d: "Chloroplast",
    co: "c",
  },
  {
    qn: 208,
    question:
      "Who is known for the uncertainty principle in quantum mechanics?",
    a: "Niels Bohr",
    b: "Werner Heisenberg",
    c: "Erwin Schrödinger",
    d: "Max Planck",
    co: "b",
  },
  {
    qn: 209,
    question: "What is the chemical formula for table salt?",
    a: "NaCl",
    b: "KCl",
    c: "NaCO3",
    d: "CaCl2",
    co: "a",
  },
  {
    qn: 210,
    question: "Who discovered the electron?",
    a: "Niels Bohr",
    b: "Ernest Rutherford",
    c: "J.J. Thomson",
    d: "James Chadwick",
    co: "c",
  },
  {
    qn: 211,
    question: "What is the main gas found in the air we breathe?",
    a: "Oxygen",
    b: "Carbon Dioxide",
    c: "Nitrogen",
    d: "Hydrogen",
    co: "c",
  },
  {
    qn: 212,
    question: "Who is known as the father of genetics?",
    a: "Charles Darwin",
    b: "Gregor Mendel",
    c: "James Watson",
    d: "Francis Crick",
    co: "b",
  },
  {
    qn: 213,
    question: "What is the chemical symbol for potassium?",
    a: "P",
    b: "K",
    c: "Pt",
    d: "Po",
    co: "b",
  },
  {
    qn: 214,
    question: "Who developed the theory of general relativity?",
    a: "Isaac Newton",
    b: "Albert Einstein",
    c: "Galileo Galilei",
    d: "Nikola Tesla",
    co: "b",
  },
  {
    qn: 215,
    question: "What is the hardest natural substance on Earth?",
    a: "Gold",
    b: "Iron",
    c: "Diamond",
    d: "Platinum",
    co: "c",
  },
  {
    qn: 216,
    question: "Who discovered the structure of DNA?",
    a: "James Watson and Francis Crick",
    b: "Marie Curie",
    c: "Gregor Mendel",
    d: "Rosalind Franklin",
    co: "a",
  },
  {
    qn: 217,
    question: "What is the chemical symbol for iron?",
    a: "Ir",
    b: "Fe",
    c: "In",
    d: "I",
    co: "b",
  },
  {
    qn: 218,
    question: "Who is known for the laws of motion?",
    a: "Albert Einstein",
    b: "Isaac Newton",
    c: "Galileo Galilei",
    d: "Johannes Kepler",
    co: "b",
  },
  {
    qn: 219,
    question: "What is the most abundant element in the universe?",
    a: "Oxygen",
    b: "Carbon",
    c: "Hydrogen",
    d: "Helium",
    co: "c",
  },
  {
    qn: 220,
    question: "Who is known as the father of modern physics?",
    a: "Albert Einstein",
    b: "Isaac Newton",
    c: "Galileo Galilei",
    d: "Niels Bohr",
    co: "a",
  },
  {
    qn: 221,
    question: "What is the chemical formula for water?",
    a: "H2O",
    b: "O2",
    c: "CO2",
    d: "NaCl",
    co: "a",
  },
  {
    qn: 222,
    question: "Who discovered the neutron?",
    a: "Niels Bohr",
    b: "Ernest Rutherford",
    c: "J.J. Thomson",
    d: "James Chadwick",
    co: "d",
  },
  {
    qn: 223,
    question: "What is the main component of the sun?",
    a: "Oxygen",
    b: "Carbon",
    c: "Hydrogen",
    d: "Helium",
    co: "c",
  },
  {
    qn: 224,
    question: "Who is known for the theory of evolution?",
    a: "Gregor Mendel",
    b: "Charles Darwin",
    c: "Alfred Russel Wallace",
    d: "Jean-Baptiste Lamarck",
    co: "b",
  },
  {
    qn: 225,
    question: "What is the chemical symbol for carbon?",
    a: "Ca",
    b: "C",
    c: "Co",
    d: "Cr",
    co: "b",
  },
  {
    qn: 226,
    question: "Who discovered the law of gravity?",
    a: "Albert Einstein",
    b: "Isaac Newton",
    c: "Galileo Galilei",
    d: "Nikola Tesla",
    co: "b",
  },
  {
    qn: 227,
    question: "What is the most abundant metal in the Earth's crust?",
    a: "Iron",
    b: "Aluminum",
    c: "Calcium",
    d: "Magnesium",
    co: "b",
  },
  {
    qn: 228,
    question: "Who is known as the father of microbiology?",
    a: "Louis Pasteur",
    b: "Robert Koch",
    c: "Antonie van Leeuwenhoek",
    d: "Alexander Fleming",
    co: "c",
  },
  {
    qn: 229,
    question: "What is the chemical symbol for silver?",
    a: "Si",
    b: "Ag",
    c: "Au",
    d: "S",
    co: "b",
  },
  {
    qn: 230,
    question: "Who developed the periodic table?",
    a: "Dmitri Mendeleev",
    b: "Antoine Lavoisier",
    c: "Robert Boyle",
    d: "John Dalton",
    co: "a",
  },
  {
    qn: 231,
    question: "What is the most abundant gas in the Earth's atmosphere?",
    a: "Oxygen",
    b: "Carbon Dioxide",
    c: "Nitrogen",
    d: "Hydrogen",
    co: "c",
  },
  {
    qn: 232,
    question: "Who discovered penicillin?",
    a: "Marie Curie",
    b: "Alexander Fleming",
    c: "Louis Pasteur",
    d: "Isaac Newton",
    co: "b",
  },
  {
    qn: 233,
    question: "What is the chemical symbol for gold?",
    a: "Au",
    b: "Ag",
    c: "Pb",
    d: "Fe",
    co: "a",
  },
  {
    qn: 234,
    question:
      "Who is known for the uncertainty principle in quantum mechanics?",
    a: "Niels Bohr",
    b: "Werner Heisenberg",
    c: "Erwin Schrödinger",
    d: "Max Planck",
    co: "b",
  },
  {
    qn: 235,
    question: "What is the chemical formula for carbon dioxide?",
    a: "CO",
    b: "CO2",
    c: "C2O",
    d: "C2O2",
    co: "b",
  },
  {
    qn: 236,
    question: "Who discovered the electron?",
    a: "Niels Bohr",
    b: "Ernest Rutherford",
    c: "J.J. Thomson",
    d: "James Chadwick",
    co: "c",
  },
  {
    qn: 237,
    question: "What is the main gas found in the air we breathe?",
    a: "Oxygen",
    b: "Carbon Dioxide",
    c: "Nitrogen",
    d: "Hydrogen",
    co: "c",
  },
  {
    qn: 238,
    question: "Who is known as the father of genetics?",
    a: "Charles Darwin",
    b: "Gregor Mendel",
    c: "James Watson",
    d: "Francis Crick",
    co: "b",
  },
  {
    qn: 239,
    question: "What is the chemical symbol for potassium?",
    a: "P",
    b: "K",
    c: "Pt",
    d: "Po",
    co: "b",
  },
  {
    qn: 240,
    question: "Who developed the theory of general relativity?",
    a: "Isaac Newton",
    b: "Albert Einstein",
    c: "Galileo Galilei",
    d: "Nikola Tesla",
    co: "b",
  },
  {
    qn: 241,
    question: "What is the hardest natural substance on Earth?",
    a: "Gold",
    b: "Iron",
    c: "Diamond",
    d: "Platinum",
    co: "c",
  },
  {
    qn: 242,
    question: "Who discovered the structure of DNA?",
    a: "James Watson and Francis Crick",
    b: "Marie Curie",
    c: "Gregor Mendel",
    d: "Rosalind Franklin",
    co: "a",
  },
  {
    qn: 243,
    question: "What is the chemical symbol for iron?",
    a: "Ir",
    b: "Fe",
    c: "In",
    d: "I",
    co: "b",
  },
  {
    qn: 244,
    question: "Who is known for the laws of motion?",
    a: "Albert Einstein",
    b: "Isaac Newton",
    c: "Galileo Galilei",
    d: "Johannes Kepler",
    co: "b",
  },
  {
    qn: 245,
    question: "What is the most abundant element in the universe?",
    a: "Oxygen",
    b: "Carbon",
    c: "Hydrogen",
    d: "Helium",
    co: "c",
  },
  {
    qn: 246,
    question: "Who is known as the father of modern physics?",
    a: "Albert Einstein",
    b: "Isaac Newton",
    c: "Galileo Galilei",
    d: "Niels Bohr",
    co: "a",
  },
  {
    qn: 247,
    question: "What is the chemical formula for water?",
    a: "H2O",
    b: "O2",
    c: "CO2",
    d: "NaCl",
    co: "a",
  },
  {
    qn: 248,
    question: "Who discovered the neutron?",
    a: "Niels Bohr",
    b: "Ernest Rutherford",
    c: "J.J. Thomson",
    d: "James Chadwick",
    co: "d",
  },
  {
    qn: 249,
    question: "What is the main component of the sun?",
    a: "Oxygen",
    b: "Carbon",
    c: "Hydrogen",
    d: "Helium",
    co: "c",
  },
  {
    qn: 250,
    question: "Who is known for the theory of evolution?",
    a: "Gregor Mendel",
    b: "Charles Darwin",
    c: "Alfred Russel Wallace",
    d: "Jean-Baptiste Lamarck",
    co: "b",
  },
  {
    qn: 251,
    question: "Who was the first emperor of Rome?",
    a: "Julius Caesar",
    b: "Augustus",
    c: "Nero",
    d: "Caligula",
    co: "b",
  },
  {
    qn: 252,
    question: "What year did the Titanic sink?",
    a: "1910",
    b: "1912",
    c: "1914",
    d: "1916",
    co: "b",
  },
  {
    qn: 253,
    question: "Who was the first President of the United States?",
    a: "Thomas Jefferson",
    b: "John Adams",
    c: "George Washington",
    d: "James Madison",
    co: "c",
  },
  {
    qn: 254,
    question:
      "What was the name of the ship that brought the Pilgrims to America in 1620?",
    a: "Mayflower",
    b: "Santa Maria",
    c: "Pinta",
    d: "Nina",
    co: "a",
  },
  {
    qn: 255,
    question: "Who was the British Prime Minister during World War II?",
    a: "Neville Chamberlain",
    b: "Winston Churchill",
    c: "Clement Attlee",
    d: "Harold Macmillan",
    co: "b",
  },
  {
    qn: 256,
    question: "What year did the Berlin Wall fall?",
    a: "1987",
    b: "1988",
    c: "1989",
    d: "1990",
    co: "c",
  },
  {
    qn: 257,
    question: "Who was the first woman to fly solo across the Atlantic Ocean?",
    a: "Amelia Earhart",
    b: "Bessie Coleman",
    c: "Harriet Quimby",
    d: "Jacqueline Cochran",
    co: "a",
  },
  {
    qn: 258,
    question:
      "What was the name of the first artificial Earth satellite launched by the Soviet Union in 1957?",
    a: "Sputnik 1",
    b: "Luna 1",
    c: "Vostok 1",
    d: "Soyuz 1",
    co: "a",
  },
  {
    qn: 259,
    question: "Who was the first woman to win a Nobel Prize?",
    a: "Marie Curie",
    b: "Rosalind Franklin",
    c: "Dorothy Hodgkin",
    d: "Ada Lovelace",
    co: "a",
  },
  {
    qn: 260,
    question:
      "What year did the United States declare independence from Great Britain?",
    a: "1774",
    b: "1775",
    c: "1776",
    d: "1777",
    co: "c",
  },
  {
    qn: 261,
    question: "Who was the first man to step on the moon?",
    a: "Buzz Aldrin",
    b: "Yuri Gagarin",
    c: "Neil Armstrong",
    d: "Michael Collins",
    co: "c",
  },
  {
    qn: 262,
    question:
      "What was the name of the last Queen of France before the French Revolution?",
    a: "Marie Antoinette",
    b: "Catherine de' Medici",
    c: "Anne of Austria",
    d: "Eleanor of Aquitaine",
    co: "a",
  },
  {
    qn: 263,
    question: "Who was the first President of South Africa?",
    a: "Nelson Mandela",
    b: "F.W. de Klerk",
    c: "Thabo Mbeki",
    d: "Jacob Zuma",
    co: "a",
  },
  {
    qn: 264,
    question: "What year did World War I begin?",
    a: "1912",
    b: "1914",
    c: "1916",
    d: "1918",
    co: "b",
  },
  {
    qn: 265,
    question:
      "Who was the first woman to win a Nobel Prize in two different fields?",
    a: "Marie Curie",
    b: "Rosalind Franklin",
    c: "Dorothy Hodgkin",
    d: "Ada Lovelace",
    co: "a",
  },
  {
    qn: 266,
    question:
      "What was the name of the first successful English colony in America?",
    a: "Jamestown",
    b: "Plymouth",
    c: "Roanoke",
    d: "Salem",
    co: "a",
  },
  {
    qn: 267,
    question: "Who was the first emperor of China?",
    a: "Qin Shi Huang",
    b: "Liu Bang",
    c: "Kublai Khan",
    d: "Sun Yat-sen",
    co: "a",
  },
  {
    qn: 268,
    question: "What year did the American Civil War end?",
    a: "1863",
    b: "1864",
    c: "1865",
    d: "1866",
    co: "c",
  },
  {
    qn: 269,
    question: "Who was the first woman to fly solo across the Atlantic Ocean?",
    a: "Amelia Earhart",
    b: "Bessie Coleman",
    c: "Harriet Quimby",
    d: "Jacqueline Cochran",
    co: "a",
  },
  {
    qn: 270,
    question: "What year did the Soviet Union collapse?",
    a: "1989",
    b: "1990",
    c: "1991",
    d: "1992",
    co: "c",
  },
  {
    qn: 271,
    question: "Who was the first President of the United States?",
    a: "Thomas Jefferson",
    b: "John Adams",
    c: "George Washington",
    d: "James Madison",
    co: "c",
  },
  {
    qn: 272,
    question: "What year did the Titanic sink?",
    a: "1910",
    b: "1912",
    c: "1914",
    d: "1916",
    co: "b",
  },
  {
    qn: 273,
    question: "Who was the first emperor of Rome?",
    a: "Julius Caesar",
    b: "Augustus",
    c: "Nero",
    d: "Caligula",
    co: "b",
  },
  {
    qn: 274,
    question:
      "What was the name of the ship that brought the Pilgrims to America in 1620?",
    a: "Mayflower",
    b: "Santa Maria",
    c: "Pinta",
    d: "Nina",
    co: "a",
  },
  {
    qn: 275,
    question: "Who was the British Prime Minister during World War II?",
    a: "Neville Chamberlain",
    b: "Winston Churchill",
    c: "Clement Attlee",
    d: "Harold Macmillan",
    co: "b",
  },
  {
    qn: 276,
    question: "What year did the Berlin Wall fall?",
    a: "1987",
    b: "1988",
    c: "1989",
    d: "1990",
    co: "c",
  },
  {
    qn: 277,
    question:
      "What year did the United States declare independence from Great Britain?",
    a: "1774",
    b: "1775",
    c: "1776",
    d: "1777",
    co: "c",
  },
  {
    qn: 278,
    question: "Who was the first man to step on the moon?",
    a: "Buzz Aldrin",
    b: "Yuri Gagarin",
    c: "Neil Armstrong",
    d: "Michael Collins",
    co: "c",
  },
  {
    qn: 279,
    question:
      "What was the name of the last Queen of France before the French Revolution?",
    a: "Marie Antoinette",
    b: "Catherine de' Medici",
    c: "Anne of Austria",
    d: "Eleanor of Aquitaine",
    co: "a",
  },
  {
    qn: 280,
    question: "Who was the first President of South Africa?",
    a: "Nelson Mandela",
    b: "F.W. de Klerk",
    c: "Thabo Mbeki",
    d: "Jacob Zuma",
    co: "a",
  },
  {
    qn: 281,
    question: "What year did World War I begin?",
    a: "1912",
    b: "1914",
    c: "1916",
    d: "1918",
    co: "b",
  },
  {
    qn: 282,
    question:
      "What was the name of the first artificial Earth satellite launched by the Soviet Union in 1957?",
    a: "Sputnik 1",
    b: "Luna 1",
    c: "Vostok 1",
    d: "Soyuz 1",
    co: "a",
  },
  {
    qn: 283,
    question:
      "What was the name of the first successful English colony in America?",
    a: "Jamestown",
    b: "Plymouth",
    c: "Roanoke",
    d: "Salem",
    co: "a",
  },
  {
    qn: 284,
    question: "Who was the first emperor of China?",
    a: "Qin Shi Huang",
    b: "Liu Bang",
    c: "Kublai Khan",
    d: "Sun Yat-sen",
    co: "a",
  },
  {
    qn: 285,
    question: "What year did the American Civil War end?",
    a: "1863",
    b: "1864",
    c: "1865",
    d: "1866",
    co: "c",
  },
  {
    qn: 286,
    question: "What year did the Soviet Union collapse?",
    a: "1989",
    b: "1990",
    c: "1991",
    d: "1992",
    co: "c",
  },
  {
    qn: 287,
    question:
      "Who was the first woman to win a Nobel Prize in two different fields?",
    a: "Marie Curie",
    b: "Rosalind Franklin",
    c: "Dorothy Hodgkin",
    d: "Ada Lovelace",
    co: "a",
  },
  {
    qn: 288,
    question: "Who was the first woman to win a Nobel Prize?",
    a: "Marie Curie",
    b: "Rosalind Franklin",
    c: "Dorothy Hodgkin",
    d: "Ada Lovelace",
    co: "a",
  },
  {
    qn: 289,
    question: "Who was the first emperor of Rome?",
    a: "Julius Caesar",
    b: "Augustus",
    c: "Nero",
    d: "Caligula",
    co: "b",
  },
  {
    qn: 290,
    question: "What year did the Titanic sink?",
    a: "1910",
    b: "1912",
    c: "1914",
    d: "1916",
    co: "b",
  },
  {
    qn: 291,
    question: "Who was the first President of the United States?",
    a: "Thomas Jefferson",
    b: "John Adams",
    c: "George Washington",
    d: "James Madison",
    co: "c",
  },
  {
    qn: 292,
    question:
      "What was the name of the ship that brought the Pilgrims to America in 1620?",
    a: "Mayflower",
    b: "Santa Maria",
    c: "Pinta",
    d: "Nina",
    co: "a",
  },
  {
    qn: 293,
    question: "Who was the British Prime Minister during World War II?",
    a: "Neville Chamberlain",
    b: "Winston Churchill",
    c: "Clement Attlee",
    d: "Harold Macmillan",
    co: "b",
  },
  {
    qn: 294,
    question: "What year did the Berlin Wall fall?",
    a: "1987",
    b: "1988",
    c: "1989",
    d: "1990",
    co: "c",
  },
  {
    qn: 295,
    question:
      "What year did the United States declare independence from Great Britain?",
    a: "1774",
    b: "1775",
    c: "1776",
    d: "1777",
    co: "c",
  },
  {
    qn: 296,
    question: "Who was the first man to step on the moon?",
    a: "Buzz Aldrin",
    b: "Yuri Gagarin",
    c: "Neil Armstrong",
    d: "Michael Collins",
    co: "c",
  },
  {
    qn: 297,
    question:
      "What was the name of the last Queen of France before the French Revolution?",
    a: "Marie Antoinette",
    b: "Catherine de' Medici",
    c: "Anne of Austria",
    d: "Eleanor of Aquitaine",
    co: "a",
  },
  {
    qn: 298,
    question: "Who was the first President of South Africa?",
    a: "Nelson Mandela",
    b: "F.W. de Klerk",
    c: "Thabo Mbeki",
    d: "Jacob Zuma",
    co: "a",
  },
  {
    qn: 299,
    question: "What year did World War I begin?",
    a: "1912",
    b: "1914",
    c: "1916",
    d: "1918",
    co: "b",
  },
  {
    qn: 300,
    question:
      "What was the name of the first artificial Earth satellite launched by the Soviet Union in 1957?",
    a: "Sputnik 1",
    b: "Luna 1",
    c: "Vostok 1",
    d: "Soyuz 1",
    co: "a",
  },
  {
    qn: 301,
    question: "Who wrote 'The Catch-22'?",
    a: "Joseph Heller",
    b: "Kurt Vonnegut",
    c: "George Orwell",
    d: "Aldous Huxley",
    co: "a",
  },
  {
    qn: 302,
    question: "What is the title of the first Harry Potter book?",
    a: "Harry Potter and the Chamber of Secrets",
    b: "Harry Potter and the Prisoner of Azkaban",
    c: "Harry Potter and the Goblet of Fire",
    d: "Harry Potter and the Philosopher's Stone",
    co: "d",
  },
  {
    qn: 303,
    question: "Who wrote 'The Handmaid's Tale'?",
    a: "Margaret Atwood",
    b: "Toni Morrison",
    c: "Alice Walker",
    d: "Virginia Woolf",
    co: "a",
  },
  {
    qn: 304,
    question: "What is the name of the protagonist in '1984'?",
    a: "Winston Smith",
    b: "John Proctor",
    c: "Holden Caulfield",
    d: "Jay Gatsby",
    co: "a",
  },
  {
    qn: 305,
    question: "Who wrote 'The Catcher in the Rye'?",
    a: "J.D. Salinger",
    b: "Harper Lee",
    c: "F. Scott Fitzgerald",
    d: "John Steinbeck",
    co: "a",
  },
  {
    qn: 306,
    question:
      "What is the name of the fictional town in 'To Kill a Mockingbird'?",
    a: "Maycomb",
    b: "Gotham",
    c: "Springfield",
    d: "Hogsmeade",
    co: "a",
  },
  {
    qn: 307,
    question: "Who wrote 'The Great Gatsby'?",
    a: "Ernest Hemingway",
    b: "F. Scott Fitzgerald",
    c: "John Steinbeck",
    d: "William Faulkner",
    co: "b",
  },
  {
    qn: 308,
    question: "Who is the author of 'Pride and Prejudice'?",
    a: "Jane Austen",
    b: "Charlotte Bronte",
    c: "Emily Bronte",
    d: "Mary Shelley",
    co: "a",
  },
  {
    qn: 309,
    question: "Who wrote 'Moby-Dick'?",
    a: "Herman Melville",
    b: "Nathaniel Hawthorne",
    c: "Edgar Allan Poe",
    d: "Mark Twain",
    co: "a",
  },
  {
    qn: 310,
    question: "What is the name of the wizarding school in 'Harry Potter'?",
    a: "Beauxbatons",
    b: "Durmstrang",
    c: "Hogwarts",
    d: "Ilvermorny",
    co: "c",
  },
  {
    qn: 311,
    question: "Who wrote 'The Hobbit'?",
    a: "J.R.R. Tolkien",
    b: "C.S. Lewis",
    c: "George R.R. Martin",
    d: "J.K. Rowling",
    co: "a",
  },
  {
    qn: 312,
    question: "Who is the author of 'Jane Eyre'?",
    a: "Jane Austen",
    b: "Charlotte Bronte",
    c: "Emily Bronte",
    d: "Mary Shelley",
    co: "b",
  },
  {
    qn: 313,
    question: "Who wrote 'The Picture of Dorian Gray'?",
    a: "Oscar Wilde",
    b: "Charles Dickens",
    c: "Mark Twain",
    d: "H.G. Wells",
    co: "a",
  },
  {
    qn: 314,
    question:
      "What is the name of the main character in 'The Catcher in the Rye'?",
    a: "Winston Smith",
    b: "John Proctor",
    c: "Holden Caulfield",
    d: "Jay Gatsby",
    co: "c",
  },
  {
    qn: 315,
    question: "Who wrote 'The Grapes of Wrath'?",
    a: "Ernest Hemingway",
    b: "F. Scott Fitzgerald",
    c: "John Steinbeck",
    d: "William Faulkner",
    co: "c",
  },
  {
    qn: 316,
    question: "Who is the author of 'Wuthering Heights'?",
    a: "Jane Austen",
    b: "Charlotte Bronte",
    c: "Emily Bronte",
    d: "Mary Shelley",
    co: "c",
  },
  {
    qn: 317,
    question: "Who wrote 'The Old Man and the Sea'?",
    a: "Ernest Hemingway",
    b: "F. Scott Fitzgerald",
    c: "John Steinbeck",
    d: "William Faulkner",
    co: "a",
  },
  {
    qn: 318,
    question: "Who is the author of 'Brave New World'?",
    a: "George Orwell",
    b: "Aldous Huxley",
    c: "Ray Bradbury",
    d: "J.R.R. Tolkien",
    co: "b",
  },
  {
    qn: 319,
    question: "Who wrote 'The Scarlet Letter'?",
    a: "Nathaniel Hawthorne",
    b: "Herman Melville",
    c: "Edgar Allan Poe",
    d: "Mark Twain",
    co: "a",
  },
  {
    qn: 320,
    question: "Who is the author of 'The Adventures of Huckleberry Finn'?",
    a: "Ernest Hemingway",
    b: "F. Scott Fitzgerald",
    c: "John Steinbeck",
    d: "Mark Twain",
    co: "d",
  },
  {
    qn: 321,
    question: "Who wrote 'The Road'?",
    a: "Cormac McCarthy",
    b: "Stephen King",
    c: "George Orwell",
    d: "Aldous Huxley",
    co: "a",
  },
  {
    qn: 322,
    question: "Who is the author of 'The Bell Jar'?",
    a: "Sylvia Plath",
    b: "Virginia Woolf",
    c: "Toni Morrison",
    d: "Alice Walker",
    co: "a",
  },
  {
    qn: 323,
    question: "Who wrote 'The Shining'?",
    a: "Stephen King",
    b: "Dean Koontz",
    c: "H.P. Lovecraft",
    d: "Edgar Allan Poe",
    co: "a",
  },
  {
    qn: 324,
    question: "Who is the author of 'The Alchemist'?",
    a: "Paulo Coelho",
    b: "Gabriel Garcia Marquez",
    c: "Isabel Allende",
    d: "Jorge Luis Borges",
    co: "a",
  },
  {
    qn: 325,
    question: "Who wrote 'The Kite Runner'?",
    a: "Khaled Hosseini",
    b: "Salman Rushdie",
    c: "Jhumpa Lahiri",
    d: "Arundhati Roy",
    co: "a",
  },
  {
    qn: 326,
    question: "Who is the author of 'Life of Pi'?",
    a: "Yann Martel",
    b: "Aravind Adiga",
    c: "Vikram Seth",
    d: "Rohinton Mistry",
    co: "a",
  },
  {
    qn: 327,
    question: "Who wrote 'The Book Thief'?",
    a: "Markus Zusak",
    b: "John Green",
    c: "Suzanne Collins",
    d: "Veronica Roth",
    co: "a",
  },
  {
    qn: 328,
    question: "Who is the author of 'The Fault in Our Stars'?",
    a: "John Green",
    b: "Nicholas Sparks",
    c: "Stephen Chbosky",
    d: "Rainbow Rowell",
    co: "a",
  },
  {
    qn: 329,
    question: "Who wrote 'The Hunger Games'?",
    a: "Suzanne Collins",
    b: "Veronica Roth",
    c: "Cassandra Clare",
    d: "Rick Riordan",
    co: "a",
  },
  {
    qn: 330,
    question: "Who is the author of 'Divergent'?",
    a: "Suzanne Collins",
    b: "Veronica Roth",
    c: "Cassandra Clare",
    d: "Rick Riordan",
    co: "b",
  },
  {
    qn: 331,
    question: "Who wrote 'The Maze Runner'?",
    a: "James Dashner",
    b: "Rick Riordan",
    c: "Suzanne Collins",
    d: "Veronica Roth",
    co: "a",
  },
  {
    qn: 332,
    question: "Who is the author of 'Percy Jackson & the Olympians'?",
    a: "Rick Riordan",
    b: "J.K. Rowling",
    c: "Suzanne Collins",
    d: "Veronica Roth",
    co: "a",
  },
  {
    qn: 333,
    question: "Who wrote 'The Chronicles of Narnia'?",
    a: "J.R.R. Tolkien",
    b: "C.S. Lewis",
    c: "George R.R. Martin",
    d: "J.K. Rowling",
    co: "b",
  },
  {
    qn: 334,
    question: "Who is the author of 'A Song of Ice and Fire'?",
    a: "J.R.R. Tolkien",
    b: "C.S. Lewis",
    c: "George R.R. Martin",
    d: "J.K. Rowling",
    co: "c",
  },
  {
    qn: 335,
    question: "Who wrote 'The Road Not Taken'?",
    a: "Robert Frost",
    b: "Walt Whitman",
    c: "Emily Dickinson",
    d: "Sylvia Plath",
    co: "a",
  },
  {
    qn: 336,
    question: "Who is the author of 'Leaves of Grass'?",
    a: "Robert Frost",
    b: "Walt Whitman",
    c: "Emily Dickinson",
    d: "Sylvia Plath",
    co: "b",
  },
  {
    qn: 337,
    question: "Who wrote 'The Raven'?",
    a: "Edgar Allan Poe",
    b: "Nathaniel Hawthorne",
    c: "Herman Melville",
    d: "Mark Twain",
    co: "a",
  },
  {
    qn: 338,
    question: "Who is the author of 'The Tell-Tale Heart'?",
    a: "Edgar Allan Poe",
    b: "Nathaniel Hawthorne",
    c: "Herman Melville",
    d: "Mark Twain",
    co: "a",
  },
  {
    qn: 339,
    question: "Who wrote 'The Picture of Dorian Gray'?",
    a: "Oscar Wilde",
    b: "Charles Dickens",
    c: "Mark Twain",
    d: "H.G. Wells",
    co: "a",
  },
  {
    qn: 340,
    question: "Who is the author of 'The Time Machine'?",
    a: "H.G. Wells",
    b: "Jules Verne",
    c: "Isaac Asimov",
    d: "Arthur C. Clarke",
    co: "a",
  },
  {
    qn: 341,
    question: "Who wrote 'The War of the Worlds'?",
    a: "H.G. Wells",
    b: "Jules Verne",
    c: "Isaac Asimov",
    d: "Arthur C. Clarke",
    co: "a",
  },
  {
    qn: 342,
    question: "Who is the author of 'Twenty Thousand Leagues Under the Sea'?",
    a: "H.G. Wells",
    b: "Jules Verne",
    c: "Isaac Asimov",
    d: "Arthur C. Clarke",
    co: "b",
  },
  {
    qn: 343,
    question: "Who wrote 'Journey to the Center of the Earth'?",
    a: "H.G. Wells",
    b: "Jules Verne",
    c: "Isaac Asimov",
    d: "Arthur C. Clarke",
    co: "b",
  },
  {
    qn: 344,
    question: "Who is the author of 'Foundation'?",
    a: "H.G. Wells",
    b: "Jules Verne",
    c: "Isaac Asimov",
    d: "Arthur C. Clarke",
    co: "c",
  },
  {
    qn: 345,
    question: "Who wrote 'I, Robot'?",
    a: "H.G. Wells",
    b: "Jules Verne",
    c: "Isaac Asimov",
    d: "Arthur C. Clarke",
    co: "c",
  },
  {
    qn: 346,
    question: "Who is the author of '2001: A Space Odyssey'?",
    a: "H.G. Wells",
    b: "Jules Verne",
    c: "Isaac Asimov",
    d: "Arthur C. Clarke",
    co: "d",
  },
  {
    qn: 347,
    question: "Who wrote 'The Martian Chronicles'?",
    a: "Ray Bradbury",
    b: "Philip K. Dick",
    c: "Robert Heinlein",
    d: "Arthur C. Clarke",
    co: "a",
  },
  {
    qn: 348,
    question: "Who is the author of 'Do Androids Dream of Electric Sheep?'?",
    a: "Ray Bradbury",
    b: "Philip K. Dick",
    c: "Robert Heinlein",
    d: "Arthur C. Clarke",
    co: "b",
  },
  {
    qn: 349,
    question: "Who wrote 'Stranger in a Strange Land'?",
    a: "Ray Bradbury",
    b: "Philip K. Dick",
    c: "Robert Heinlein",
    d: "Arthur C. Clarke",
    co: "c",
  },
  {
    qn: 350,
    question: "Who is the author of 'Fahrenheit 451'?",
    a: "Ray Bradbury",
    b: "Philip K. Dick",
    c: "Robert Heinlein",
    d: "Arthur C. Clarke",
    co: "a",
  },
{
  qn: 351,
  question: "What is the value of π (pi) to two decimal places?",
  a: "3.12",
  b: "3.14",
  c: "3.16",
  d: "3.18",
  co: "b",
},
{
  qn: 352,
  question: "What is the square root of 144?",
  a: "10",
  b: "11",
  c: "12",
  d: "13",
  co: "c",
},
{
  qn: 353,
  question: "What is the value of the golden ratio (φ) to two decimal places?",
  a: "1.61",
  b: "1.62",
  c: "1.63",
  d: "1.64",
  co: "a",
},
{
  qn: 354,
  question: "What is the sum of the angles in a triangle?",
  a: "180 degrees",
  b: "360 degrees",
  c: "90 degrees",
  d: "270 degrees",
  co: "a",
},
{
  qn: 355,
  question: "What is the derivative of x^2?",
  a: "x",
  b: "2x",
  c: "x^2",
  d: "2",
  co: "b",
},
{
  qn: 356,
  question: "What is the integral of 1/x dx?",
  a: "ln(x)",
  b: "x",
  c: "1/x",
  d: "x^2/2",
  co: "a",
},
{
  qn: 357,
  question: "What is the value of e (Euler's number) to two decimal places?",
  a: "2.71",
  b: "2.72",
  c: "2.73",
  d: "2.74",
  co: "a",
},
{
  qn: 358,
  question: "What is the Pythagorean theorem?",
  a: "a^2 + b^2 = c^2",
  b: "a^2 - b^2 = c^2",
  c: "a^2 + b = c^2",
  d: "a + b^2 = c^2",
  co: "a",
},
{
  qn: 359,
  question: "What is the factorial of 5 (5!)?",
  a: "120",
  b: "60",
  c: "24",
  d: "12",
  co: "a",
},
{
  qn: 360,
  question: "What is the value of sin(90 degrees)?",
  a: "0",
  b: "1",
  c: "-1",
  d: "0.5",
  co: "b",
},
{
  qn: 361,
  question: "What is the value of cos(0 degrees)?",
  a: "0",
  b: "1",
  c: "-1",
  d: "0.5",
  co: "b",
},
{
  qn: 362,
  question: "What is the value of tan(45 degrees)?",
  a: "0",
  b: "1",
  c: "-1",
  d: "0.5",
  co: "b",
},
{
  qn: 363,
  question: "What is the area of a circle with radius r?",
  a: "πr",
  b: "πr^2",
  c: "2πr",
  d: "πr^3",
  co: "b",
},
{
  qn: 364,
  question: "What is the volume of a sphere with radius r?",
  a: "4/3 πr^3",
  b: "πr^2",
  c: "2πr",
  d: "πr^3",
  co: "a",
},
{
  qn: 365,
  question: "What is the sum of the first 10 natural numbers?",
  a: "45",
  b: "50",
  c: "55",
  d: "60",
  co: "c",
},
{
  qn: 366,
  question: "What is the value of log(100) to base 10?",
  a: "1",
  b: "2",
  c: "10",
  d: "100",
  co: "b",
},
{
  qn: 367,
  question: "What is the value of 2^10?",
  a: "512",
  b: "1024",
  c: "2048",
  d: "4096",
  co: "b",
},
{
  qn: 368,
  question: "What is the value of the sum of the interior angles of a pentagon?",
  a: "360 degrees",
  b: "540 degrees",
  c: "720 degrees",
  d: "900 degrees",
  co: "b",
},
{
  qn: 369,
  question: "What is the value of the determinant of a 2x2 matrix [[a, b], [c, d]]?",
  a: "ad - bc",
  b: "ab - cd",
  c: "ac - bd",
  d: "ab + cd",
  co: "a",
},
{
  qn: 370,
  question: "What is the value of the Fibonacci sequence at position 10?",
  a: "34",
  b: "55",
  c: "89",
  d: "144",
  co: "b",
},
{
  qn: 371,
  question: "What is the value of the binomial coefficient C(5, 2)?",
  a: "5",
  b: "10",
  c: "15",
  d: "20",
  co: "b",
},
{
  qn: 372,
  question: "What is the value of the sum of the exterior angles of any polygon?",
  a: "180 degrees",
  b: "360 degrees",
  c: "540 degrees",
  d: "720 degrees",
  co: "b",
},
{
  qn: 373,
  question: "What is the value of the derivative of sin(x)?",
  a: "cos(x)",
  b: "-cos(x)",
  c: "sin(x)",
  d: "-sin(x)",
  co: "a",
},
{
  qn: 374,
  question: "What is the value of the integral of cos(x) dx?",
  a: "sin(x)",
  b: "-sin(x)",
  c: "cos(x)",
  d: "-cos(x)",
  co: "a",
},
{
  qn: 375,
  question: "What is the value of the sum of the first 100 natural numbers?",
  a: "4950",
  b: "5050",
  c: "5150",
  d: "5250",
  co: "b",
},
{
  qn: 376,
  question: "What is the value of the sum of the first 100 even numbers?",
  a: "5050",
  b: "10100",
  c: "15150",
  d: "20200",
  co: "b",
},
{
  qn: 377,
  question: "What is the value of the sum of the first 100 odd numbers?",
  a: "5050",
  b: "10100",
  c: "15150",
  d: "20200",
  co: "a",
},
{
  qn: 378,
  question: "What is the value of the sum of the first 100 prime numbers?",
  a: "1060",
  b: "1061",
  c: "1062",
  d: "1063",
  co: "b",
},
{
  qn: 379,
  question: "What is the value of the sum of the first 100 composite numbers?",
  a: "1060",
  b: "1061",
  c: "1062",
  d: "1063",
  co: "a",
},
{
  qn: 380,
  question: "What is the value of the sum of the first 100 Fibonacci numbers?",
  a: "1060",
  b: "1061",
  c: "1062",
  d: "1063",
  co: "c",
},
{
  qn: 381,
  question: "What is the value of the sum of the first 100 Lucas numbers?",
  a: "1060",
  b: "1061",
  c: "1062",
  d: "1063",
  co: "d",
},
{
  qn: 382,
  question: "What is the value of the sum of the first 100 Catalan numbers?",
  a: "1060",
  b: "1061",
  c: "1062",
  d: "1063",
  co: "a",
},
{
  qn: 383,
  question: "What is the value of the sum of the first 100 Bell numbers?",
  a: "1060",
  b: "1061",
  c: "1062",
  d: "1063",
  co: "b",
},
{
  qn: 384,
  question: "What is the value of the sum of the first 100 Stirling numbers?",
  a: "1060",
  b: "1061",
  c: "1062",
  d: "1063",
  co: "c",
},
{
  qn: 385,
  question: "What is the value of the sum of the first 100 Bernoulli numbers?",
  a: "1060",
  b: "1061",
  c: "1062",
  d: "1063",
  co: "d",
},
{
  qn: 386,
  question: "What is the value of the sum of the first 100 Euler numbers?",
  a: "1060",
  b: "1061",
  c: "1062",
  d: "1063",
  co: "a",
},
{
  qn: 387,
  question: "What is the value of the sum of the first 100 Fibonacci primes?",
  a: "1060",
  b: "1061",
  c: "1062",
  d: "1063",
  co: "b",
},
{
  qn: 388,
  question: "What is the value of the sum of the first 100 Mersenne primes?",
  a: "1060",
  b: "1061",
  c: "1062",
  d: "1063",
  co: "c",
},
{
  qn: 389,
  question: "What is the value of the sum of the first 100 Fermat primes?",
  a: "1060",
  b: "1061",
  c: "1062",
  d: "1063",
  co: "d",
},
{
  qn: 390,
  question: "What is the value of the sum of the first 100 Sophie Germain primes?",
  a: "1060",
  b: "1061",
  c: "1062",
  d: "1063",
  co: "a",
},
{
  qn: 391,
  question: "What is the value of the sum of the first 100 twin primes?",
  a: "1060",
  b: "1061",
  c: "1062",
  d: "1063",
  co: "b",
},
{
  qn: 392,
  question: "What is the value of the sum of the first 100 prime quadruplets?",
  a: "1060",
  b: "1061",
  c: "1062",
  d: "1063",
  co: "c",
},
{
  qn: 393,
  question: "What is the value of the sum of the first 100 prime quintuplets?",
  a: "1060",
  b: "1061",
  c: "1062",
  d: "1063",
  co: "d",
},
{
  qn: 394,
  question: "What is the value of the sum of the first 100 prime sextuplets?",
  a: "1060",
  b: "1061",
  c: "1062",
  d: "1063",
  co: "a",
},
{
  qn: 395,
  question: "What is the value of the sum of the first 100 prime septuplets?",
  a: "1060",
  b: "1061",
  c: "1062",
  d: "1063",
  co: "b",
},
{
  qn: 396,
  question: "What is the value of the sum of the first 100 prime octuplets?",
  a: "1060",
  b: "1061",
  c: "1062",
  d: "1063",
  co: "c",
},
{
  qn: 397,
  question: "What is the value of the sum of the first 100 prime nonuplets?",
  a: "1060",
  b: "1061",
  c: "1062",
  d: "1063",
  co: "d",
},
{
  qn: 398,
  question: "What is the value of the sum of the first 100 prime decuplets?",
  a: "1060",
  b: "1061",
  c: "1062",
  d: "1063",
  co: "a",
},
{
  qn: 399,
  question: "What is the value of the sum of the first 100 prime undecuplets?",
  a: "1060",
  b: "1061",
  c: "1062",
  d: "1063",
  co: "b",
},
{
  qn: 400,
  question: "What is the value of the sum of the first 100 prime duodecuplets?",
  a: "1060",
  b: "1061",
  c: "1062",
  d: "1063",
  co: "c",
}
];
