export const questions = [
  {
    qn: 1,
    question: "What is the capital of France?",
    a: "Berlin",
    b: "Madrid",
    c: "Paris",
    d: "Rome",
    co: "c",
  },
  {
    qn: 2,
    question: "Who wrote 'To Kill a Mockingbird'?",
    a: "Harper Lee",
    b: "Mark Twain",
    c: "Ernest Hemingway",
    d: "F. Scott Fitzgerald",
    co: "a",
  },
  {
    qn: 3,
    question: "What is the largest planet in our solar system?",
    a: "Earth",
    b: "Jupiter",
    c: "Saturn",
    d: "Mars",
    co: "b",
  },
  {
    qn: 4,
    question: "What is the smallest country in the world?",
    a: "Monaco",
    b: "Vatican City",
    c: "San Marino",
    d: "Liechtenstein",
    co: "b",
  },
  {
    qn: 5,
    question: "Who painted the Mona Lisa?",
    a: "Vincent van Gogh",
    b: "Pablo Picasso",
    c: "Leonardo da Vinci",
    d: "Claude Monet",
    co: "c",
  },
  {
    qn: 6,
    question: "What is the longest river in the world?",
    a: "Amazon River",
    b: "Nile River",
    c: "Yangtze River",
    d: "Mississippi River",
    co: "b",
  },
  {
    qn: 7,
    question: "Who discovered penicillin?",
    a: "Marie Curie",
    b: "Alexander Fleming",
    c: "Louis Pasteur",
    d: "Isaac Newton",
    co: "b",
  },
  {
    qn: 8,
    question: "What is the hardest natural substance on Earth?",
    a: "Gold",
    b: "Iron",
    c: "Diamond",
    d: "Platinum",
    co: "c",
  },
  {
    qn: 9,
    question: "What is the largest ocean on Earth?",
    a: "Atlantic Ocean",
    b: "Indian Ocean",
    c: "Arctic Ocean",
    d: "Pacific Ocean",
    co: "d",
  },
  {
    qn: 10,
    question: "Who was the first person to walk on the moon?",
    a: "Buzz Aldrin",
    b: "Yuri Gagarin",
    c: "Neil Armstrong",
    d: "Michael Collins",
    co: "c",
  },
  {
    qn: 11,
    question: "What is the chemical symbol for gold?",
    a: "Au",
    b: "Ag",
    c: "Pb",
    d: "Fe",
    co: "a",
  },
  {
    qn: 12,
    question: "Who wrote '1984'?",
    a: "George Orwell",
    b: "Aldous Huxley",
    c: "Ray Bradbury",
    d: "J.R.R. Tolkien",
    co: "a",
  },
  {
    qn: 13,
    question: "What is the capital of Japan?",
    a: "Seoul",
    b: "Beijing",
    c: "Tokyo",
    d: "Bangkok",
    co: "c",
  },
  {
    qn: 14,
    question: "What is the largest desert in the world?",
    a: "Sahara Desert",
    b: "Gobi Desert",
    c: "Kalahari Desert",
    d: "Arctic Desert",
    co: "a",
  },
  {
    qn: 15,
    question: "Who developed the theory of relativity?",
    a: "Isaac Newton",
    b: "Albert Einstein",
    c: "Galileo Galilei",
    d: "Nikola Tesla",
    co: "b",
  },
  {
    qn: 16,
    question: "What is the capital of Australia?",
    a: "Sydney",
    b: "Melbourne",
    c: "Canberra",
    d: "Brisbane",
    co: "c",
  },
  {
    qn: 17,
    question: "Who is known as the 'Father of Computers'?",
    a: "Alan Turing",
    b: "Charles Babbage",
    c: "John von Neumann",
    d: "Bill Gates",
    co: "b",
  },
  {
    qn: 18,
    question: "What is the tallest mountain in the world?",
    a: "K2",
    b: "Kangchenjunga",
    c: "Mount Everest",
    d: "Lhotse",
    co: "c",
  },
  {
    qn: 19,
    question: "Who wrote 'Pride and Prejudice'?",
    a: "Jane Austen",
    b: "Charlotte Bronte",
    c: "Emily Bronte",
    d: "Mary Shelley",
    co: "a",
  },
  {
    qn: 20,
    question: "What is the capital of Canada?",
    a: "Toronto",
    b: "Vancouver",
    c: "Ottawa",
    d: "Montreal",
    co: "c",
  },
  {
    qn: 21,
    question: "Who invented the telephone?",
    a: "Alexander Graham Bell",
    b: "Thomas Edison",
    c: "Nikola Tesla",
    d: "Guglielmo Marconi",
    co: "a",
  },
  {
    qn: 22,
    question: "What is the largest mammal in the world?",
    a: "Elephant",
    b: "Blue Whale",
    c: "Giraffe",
    d: "Hippopotamus",
    co: "b",
  },
  {
    qn: 23,
    question: "What is the capital of Italy?",
    a: "Venice",
    b: "Milan",
    c: "Rome",
    d: "Florence",
    co: "c",
  },
  {
    qn: 24,
    question: "Who wrote 'The Odyssey'?",
    a: "Homer",
    b: "Virgil",
    c: "Sophocles",
    d: "Euripides",
    co: "a",
  },
  {
    qn: 25,
    question: "What is the smallest planet in our solar system?",
    a: "Mercury",
    b: "Venus",
    c: "Mars",
    d: "Pluto",
    co: "a",
  },
  {
    qn: 26,
    question: "Who discovered America?",
    a: "Christopher Columbus",
    b: "Ferdinand Magellan",
    c: "Vasco da Gama",
    d: "James Cook",
    co: "a",
  },
  {
    qn: 27,
    question: "What is the capital of Russia?",
    a: "Saint Petersburg",
    b: "Moscow",
    c: "Kiev",
    d: "Minsk",
    co: "b",
  },
  {
    qn: 28,
    question: "Who wrote 'The Great Gatsby'?",
    a: "Ernest Hemingway",
    b: "F. Scott Fitzgerald",
    c: "John Steinbeck",
    d: "William Faulkner",
    co: "b",
  },
  {
    qn: 29,
    question: "What is the largest continent?",
    a: "Africa",
    b: "Asia",
    c: "Europe",
    d: "North America",
    co: "b",
  },
  {
    qn: 30,
    question: "Who was the first President of the United States?",
    a: "Thomas Jefferson",
    b: "John Adams",
    c: "George Washington",
    d: "James Madison",
    co: "c",
  },
  {
    qn: 31,
    question: "What is the capital of Germany?",
    a: "Munich",
    b: "Frankfurt",
    c: "Berlin",
    d: "Hamburg",
    co: "c",
  },
  {
    qn: 32,
    question: "Who wrote 'Moby-Dick'?",
    a: "Herman Melville",
    b: "Nathaniel Hawthorne",
    c: "Edgar Allan Poe",
    d: "Mark Twain",
    co: "a",
  },
  {
    qn: 33,
    question: "What is the largest island in the world?",
    a: "Greenland",
    b: "New Guinea",
    c: "Borneo",
    d: "Madagascar",
    co: "a",
  },
  {
    qn: 34,
    question: "Who invented the light bulb?",
    a: "Nikola Tesla",
    b: "Alexander Graham Bell",
    c: "Thomas Edison",
    d: "George Westinghouse",
    co: "c",
  },
  {
    qn: 35,
    question: "What is the capital of India?",
    a: "Mumbai",
    b: "New Delhi",
    c: "Bangalore",
    d: "Kolkata",
    co: "b",
  },
  {
    qn: 36,
    question: "Who wrote 'War and Peace'?",
    a: "Fyodor Dostoevsky",
    b: "Leo Tolstoy",
    c: "Anton Chekhov",
    d: "Ivan Turgenev",
    co: "b",
  },
  {
    qn: 37,
    question: "What is the largest bone in the human body?",
    a: "Femur",
    b: "Humerus",
    c: "Tibia",
    d: "Fibula",
    co: "a",
  },
  {
    qn: 38,
    question: "Who was the first woman to win a Nobel Prize?",
    a: "Marie Curie",
    b: "Rosalind Franklin",
    c: "Dorothy Hodgkin",
    d: "Ada Lovelace",
    co: "a",
  },
  {
    qn: 39,
    question: "What is the capital of Brazil?",
    a: "Rio de Janeiro",
    b: "São Paulo",
    c: "Brasília",
    d: "Salvador",
    co: "c",
  },
  {
    qn: 40,
    question: "Who wrote 'The Catcher in the Rye'?",
    a: "J.D. Salinger",
    b: "Harper Lee",
    c: "F. Scott Fitzgerald",
    d: "John Steinbeck",
    co: "a",
  },
  {
    qn: 41,
    question: "What is the largest organ in the human body?",
    a: "Heart",
    b: "Liver",
    c: "Skin",
    d: "Lungs",
    co: "c",
  },
  {
    qn: 42,
    question: "Who was the first woman to fly solo across the Atlantic Ocean?",
    a: "Amelia Earhart",
    b: "Bessie Coleman",
    c: "Harriet Quimby",
    d: "Jacqueline Cochran",
    co: "a",
  },
  {
    qn: 43,
    question: "What is the capital of Egypt?",
    a: "Cairo",
    b: "Alexandria",
    c: "Giza",
    d: "Luxor",
    co: "a",
  },
  {
    qn: 44,
    question: "Who wrote 'The Divine Comedy'?",
    a: "Geoffrey Chaucer",
    b: "Dante Alighieri",
    c: "John Milton",
    d: "Homer",
    co: "b",
  },
  {
    qn: 45,
    question: "What is the smallest bone in the human body?",
    a: "Stapes",
    b: "Incus",
    c: "Malleus",
    d: "Hyoid",
    co: "a",
  },
  {
    qn: 46,
    question: "Who was the first President of South Africa?",
    a: "Nelson Mandela",
    b: "F.W. de Klerk",
    c: "Thabo Mbeki",
    d: "Jacob Zuma",
    co: "a",
  },
  {
    qn: 47,
    question: "What is the capital of Argentina?",
    a: "Buenos Aires",
    b: "Córdoba",
    c: "Rosario",
    d: "Mendoza",
    co: "a",
  },
  {
    qn: 48,
    question: "Who wrote 'The Iliad'?",
    a: "Homer",
    b: "Virgil",
    c: "Sophocles",
    d: "Euripides",
    co: "a",
  },
  {
    qn: 49,
    question: "What is the largest muscle in the human body?",
    a: "Biceps",
    b: "Quadriceps",
    c: "Gluteus Maximus",
    d: "Trapezius",
    co: "c",
  },
  {
    qn: 50,
    question:
      "Who was the first woman to win a Nobel Prize in two different fields?",
    a: "Marie Curie",
    b: "Rosalind Franklin",
    c: "Dorothy Hodgkin",
    d: "Ada Lovelace",
    co: "a",
  },
  {
    qn: 51,
    question: "What is the capital of South Korea?",
    a: "Seoul",
    b: "Tokyo",
    c: "Beijing",
    d: "Bangkok",
    co: "a",
  },
  {
    qn: 52,
    question: "Who wrote 'The Hobbit'?",
    a: "J.R.R. Tolkien",
    b: "C.S. Lewis",
    c: "George R.R. Martin",
    d: "J.K. Rowling",
    co: "a",
  },
  {
    qn: 53,
    question: "What is the chemical symbol for water?",
    a: "H2O",
    b: "O2",
    c: "CO2",
    d: "NaCl",
    co: "a",
  },
  {
    qn: 54,
    question: "Who was the first man in space?",
    a: "Neil Armstrong",
    b: "Yuri Gagarin",
    c: "Buzz Aldrin",
    d: "John Glenn",
    co: "b",
  },
  {
    qn: 55,
    question: "What is the capital of Mexico?",
    a: "Guadalajara",
    b: "Monterrey",
    c: "Mexico City",
    d: "Cancun",
    co: "c",
  },
  {
    qn: 56,
    question: "Who wrote 'The Picture of Dorian Gray'?",
    a: "Oscar Wilde",
    b: "Charles Dickens",
    c: "Mark Twain",
    d: "H.G. Wells",
    co: "a",
  },
  {
    qn: 57,
    question: "What is the largest country by area?",
    a: "Canada",
    b: "China",
    c: "United States",
    d: "Russia",
    co: "d",
  },
  {
    qn: 58,
    question: "Who discovered the law of gravity?",
    a: "Albert Einstein",
    b: "Isaac Newton",
    c: "Galileo Galilei",
    d: "Nikola Tesla",
    co: "b",
  },
  {
    qn: 59,
    question: "What is the capital of Spain?",
    a: "Barcelona",
    b: "Madrid",
    c: "Seville",
    d: "Valencia",
    co: "b",
  },
  {
    qn: 60,
    question: "Who wrote 'The Adventures of Tom Sawyer'?",
    a: "Mark Twain",
    b: "Ernest Hemingway",
    c: "F. Scott Fitzgerald",
    d: "John Steinbeck",
    co: "a",
  },
  {
    qn: 61,
    question: "What is the smallest ocean in the world?",
    a: "Atlantic Ocean",
    b: "Indian Ocean",
    c: "Arctic Ocean",
    d: "Southern Ocean",
    co: "c",
  },
  {
    qn: 62,
    question: "Who painted the Sistine Chapel ceiling?",
    a: "Leonardo da Vinci",
    b: "Michelangelo",
    c: "Raphael",
    d: "Donatello",
    co: "b",
  },
  {
    qn: 63,
    question: "What is the capital of China?",
    a: "Shanghai",
    b: "Beijing",
    c: "Hong Kong",
    d: "Guangzhou",
    co: "b",
  },
  {
    qn: 64,
    question: "Who wrote 'The Brothers Karamazov'?",
    a: "Leo Tolstoy",
    b: "Fyodor Dostoevsky",
    c: "Anton Chekhov",
    d: "Ivan Turgenev",
    co: "b",
  },
  {
    qn: 65,
    question: "What is the largest lake in the world?",
    a: "Lake Superior",
    b: "Lake Victoria",
    c: "Caspian Sea",
    d: "Lake Baikal",
    co: "c",
  },
  {
    qn: 66,
    question: "Who discovered the structure of DNA?",
    a: "James Watson and Francis Crick",
    b: "Marie Curie",
    c: "Gregor Mendel",
    d: "Rosalind Franklin",
    co: "a",
  },
  {
    qn: 67,
    question: "What is the capital of Greece?",
    a: "Athens",
    b: "Thessaloniki",
    c: "Patras",
    d: "Heraklion",
    co: "a",
  },
  {
    qn: 68,
    question: "Who wrote 'The Count of Monte Cristo'?",
    a: "Victor Hugo",
    b: "Alexandre Dumas",
    c: "Jules Verne",
    d: "Honoré de Balzac",
    co: "b",
  },
  {
    qn: 69,
    question: "What is the largest island in the Mediterranean Sea?",
    a: "Sicily",
    b: "Sardinia",
    c: "Cyprus",
    d: "Crete",
    co: "a",
  },
  {
    qn: 70,
    question: "Who developed the polio vaccine?",
    a: "Albert Sabin",
    b: "Louis Pasteur",
    c: "Jonas Salk",
    d: "Edward Jenner",
    co: "c",
  },
  {
    qn: 71,
    question: "What is the capital of Turkey?",
    a: "Istanbul",
    b: "Ankara",
    c: "Izmir",
    d: "Antalya",
    co: "b",
  },
  {
    qn: 72,
    question: "Who wrote 'The Old Man and the Sea'?",
    a: "Ernest Hemingway",
    b: "F. Scott Fitzgerald",
    c: "John Steinbeck",
    d: "William Faulkner",
    co: "a",
  },
  {
    qn: 73,
    question: "What is the largest desert in Africa?",
    a: "Kalahari Desert",
    b: "Sahara Desert",
    c: "Namib Desert",
    d: "Libyan Desert",
    co: "b",
  },
  {
    qn: 74,
    question: "Who discovered the electron?",
    a: "Niels Bohr",
    b: "Ernest Rutherford",
    c: "J.J. Thomson",
    d: "James Chadwick",
    co: "c",
  },
  {
    qn: 75,
    question: "What is the capital of Portugal?",
    a: "Lisbon",
    b: "Porto",
    c: "Braga",
    d: "Coimbra",
    co: "a",
  },
  {
    qn: 76,
    question: "Who wrote 'The Scarlet Letter'?",
    a: "Nathaniel Hawthorne",
    b: "Herman Melville",
    c: "Edgar Allan Poe",
    d: "Mark Twain",
    co: "a",
  },
  {
    qn: 77,
    question: "What is the largest river in Africa?",
    a: "Congo River",
    b: "Niger River",
    c: "Nile River",
    d: "Zambezi River",
    co: "c",
  },
  {
    qn: 78,
    question: "Who discovered radioactivity?",
    a: "Marie Curie",
    b: "Henri Becquerel",
    c: "Ernest Rutherford",
    d: "Wilhelm Röntgen",
    co: "b",
  },
  {
    qn: 79,
    question: "What is the capital of Thailand?",
    a: "Bangkok",
    b: "Phuket",
    c: "Chiang Mai",
    d: "Pattaya",
    co: "a",
  },
  {
    qn: 80,
    question: "Who wrote 'The Canterbury Tales'?",
    a: "Geoffrey Chaucer",
    b: "William Shakespeare",
    c: "John Milton",
    d: "Christopher Marlowe",
    co: "a",
  },
  {
    qn: 81,
    question: "What is the largest volcano in the world?",
    a: "Mount Vesuvius",
    b: "Mount St. Helens",
    c: "Mauna Loa",
    d: "Mount Fuji",
    co: "c",
  },
  {
    qn: 82,
    question: "Who was the first woman to win a Nobel Prize in Literature?",
    a: "Selma Lagerlöf",
    b: "Toni Morrison",
    c: "Gabriela Mistral",
    d: "Pearl S. Buck",
    co: "a",
  },
  {
    qn: 83,
    question: "What is the capital of Saudi Arabia?",
    a: "Jeddah",
    b: "Mecca",
    c: "Riyadh",
    d: "Medina",
    co: "c",
  },
  {
    qn: 84,
    question: "Who wrote 'The Metamorphosis'?",
    a: "Franz Kafka",
    b: "Albert Camus",
    c: "Jean-Paul Sartre",
    d: "Hermann Hesse",
    co: "a",
  },
  {
    qn: 85,
    question: "What is the largest coral reef system in the world?",
    a: "Great Barrier Reef",
    b: "Belize Barrier Reef",
    c: "Red Sea Coral Reef",
    d: "New Caledonia Barrier Reef",
    co: "a",
  },
  {
    qn: 86,
    question: "Who discovered the circulation of blood?",
    a: "Andreas Vesalius",
    b: "William Harvey",
    c: "Hippocrates",
    d: "Galen",
    co: "b",
  },
  {
    qn: 87,
    question: "What is the capital of Sweden?",
    a: "Gothenburg",
    b: "Malmö",
    c: "Stockholm",
    d: "Uppsala",
    co: "c",
  },
  {
    qn: 88,
    question: "Who wrote 'The Three Musketeers'?",
    a: "Victor Hugo",
    b: "Alexandre Dumas",
    c: "Jules Verne",
    d: "Honoré de Balzac",
    co: "b",
  },
  {
    qn: 89,
    question: "What is the largest desert in Asia?",
    a: "Gobi Desert",
    b: "Arabian Desert",
    c: "Karakum Desert",
    d: "Thar Desert",
    co: "a",
  },
  {
    qn: 90,
    question: "Who developed the theory of evolution?",
    a: "Gregor Mendel",
    b: "Charles Darwin",
    c: "Alfred Russel Wallace",
    d: "Jean-Baptiste Lamarck",
    co: "b",
  },
  {
    qn: 91,
    question: "What is the capital of Norway?",
    a: "Bergen",
    b: "Trondheim",
    c: "Oslo",
    d: "Stavanger",
    co: "c",
  },
  {
    qn: 92,
    question: "Who wrote 'Crime and Punishment'?",
    a: "Leo Tolstoy",
    b: "Fyodor Dostoevsky",
    c: "Anton Chekhov",
    d: "Ivan Turgenev",
    co: "b",
  },
  {
    qn: 93,
    question: "What is the largest rainforest in the world?",
    a: "Congo Rainforest",
    b: "Amazon Rainforest",
    c: "Daintree Rainforest",
    d: "Southeast Asian Rainforest",
    co: "b",
  },
  {
    qn: 94,
    question: "Who discovered the neutron?",
    a: "Niels Bohr",
    b: "Ernest Rutherford",
    c: "J.J. Thomson",
    d: "James Chadwick",
    co: "d",
  },
  {
    qn: 95,
    question: "What is the capital of the Netherlands?",
    a: "Rotterdam",
    b: "The Hague",
    c: "Amsterdam",
    d: "Utrecht",
    co: "c",
  },
  {
    qn: 96,
    question: "Who wrote 'The Grapes of Wrath'?",
    a: "Ernest Hemingway",
    b: "F. Scott Fitzgerald",
    c: "John Steinbeck",
    d: "William Faulkner",
    co: "c",
  },
  {
    qn: 97,
    question: "What is the largest island in the Caribbean?",
    a: "Cuba",
    b: "Hispaniola",
    c: "Jamaica",
    d: "Puerto Rico",
    co: "a",
  },
  {
    qn: 98,
    question: "Who discovered the proton?",
    a: "Niels Bohr",
    b: "Ernest Rutherford",
    c: "J.J. Thomson",
    d: "James Chadwick",
    co: "b",
  },
  {
    qn: 99,
    question: "What is the capital of Switzerland?",
    a: "Zurich",
    b: "Geneva",
    c: "Bern",
    d: "Basel",
    co: "c",
  },
  {
    qn: 100,
    question: "Who wrote 'Brave New World'?",
    a: "George Orwell",
    b: "Aldous Huxley",
    c: "Ray Bradbury",
    d: "J.R.R. Tolkien",
    co: "b",
  },
{
  qn: 101,
  question: "What is the capital of South Africa?",
  a: "Johannesburg",
  b: "Pretoria",
  c: "Cape Town",
  d: "Durban",
  co: "b",
},
{
  qn: 102,
  question: "Who wrote 'The Road Not Taken'?",
  a: "Robert Frost",
  b: "Walt Whitman",
  c: "Emily Dickinson",
  d: "Sylvia Plath",
  co: "a",
},
{
  qn: 103,
  question: "What is the largest moon of Saturn?",
  a: "Europa",
  b: "Titan",
  c: "Ganymede",
  d: "Callisto",
  co: "b",
},
{
  qn: 104,
  question: "Who discovered the electron?",
  a: "Niels Bohr",
  b: "Ernest Rutherford",
  c: "J.J. Thomson",
  d: "James Chadwick",
  co: "c",
},
{
  qn: 105,
  question: "What is the capital of New Zealand?",
  a: "Auckland",
  b: "Wellington",
  c: "Christchurch",
  d: "Hamilton",
  co: "b",
},
{
  qn: 106,
  question: "Who wrote 'The Catch-22'?",
  a: "Joseph Heller",
  b: "Kurt Vonnegut",
  c: "George Orwell",
  d: "Aldous Huxley",
  co: "a",
},
{
  qn: 107,
  question: "What is the largest island in the Mediterranean Sea?",
  a: "Sicily",
  b: "Sardinia",
  c: "Cyprus",
  d: "Crete",
  co: "a",
},
{
  qn: 108,
  question: "Who developed the theory of general relativity?",
  a: "Isaac Newton",
  b: "Albert Einstein",
  c: "Galileo Galilei",
  d: "Nikola Tesla",
  co: "b",
},
{
  qn: 109,
  question: "What is the capital of Finland?",
  a: "Helsinki",
  b: "Oslo",
  c: "Stockholm",
  d: "Copenhagen",
  co: "a",
},
{
  qn: 110,
  question: "Who wrote 'The Sun Also Rises'?",
  a: "Ernest Hemingway",
  b: "F. Scott Fitzgerald",
  c: "John Steinbeck",
  d: "William Faulkner",
  co: "a",
},
{
  qn: 111,
  question: "What is the largest ocean on Earth?",
  a: "Atlantic Ocean",
  b: "Indian Ocean",
  c: "Arctic Ocean",
  d: "Pacific Ocean",
  co: "d",
},
{
  qn: 112,
  question: "Who discovered the law of gravity?",
  a: "Albert Einstein",
  b: "Isaac Newton",
  c: "Galileo Galilei",
  d: "Nikola Tesla",
  co: "b",
},
{
  qn: 113,
  question: "What is the capital of Denmark?",
  a: "Copenhagen",
  b: "Oslo",
  c: "Stockholm",
  d: "Helsinki",
  co: "a",
},
{
  qn: 114,
  question: "Who wrote 'The Great Gatsby'?",
  a: "Ernest Hemingway",
  b: "F. Scott Fitzgerald",
  c: "John Steinbeck",
  d: "William Faulkner",
  co: "b",
},
{
  qn: 115,
  question: "What is the largest desert in the world?",
  a: "Sahara Desert",
  b: "Gobi Desert",
  c: "Kalahari Desert",
  d: "Arctic Desert",
  co: "a",
},
{
  qn: 116,
  question: "Who developed the theory of evolution?",
  a: "Gregor Mendel",
  b: "Charles Darwin",
  c: "Alfred Russel Wallace",
  d: "Jean-Baptiste Lamarck",
  co: "b",
},
{
  qn: 117,
  question: "What is the capital of Norway?",
  a: "Bergen",
  b: "Trondheim",
  c: "Oslo",
  d: "Stavanger",
  co: "c",
},
{
  qn: 118,
  question: "Who wrote 'Crime and Punishment'?",
  a: "Leo Tolstoy",
  b: "Fyodor Dostoevsky",
  c: "Anton Chekhov",
  d: "Ivan Turgenev",
  co: "b",
},
{
  qn: 119,
  question: "What is the largest rainforest in the world?",
  a: "Congo Rainforest",
  b: "Amazon Rainforest",
  c: "Daintree Rainforest",
  d: "Southeast Asian Rainforest",
  co: "b",
},
{
  qn: 120,
  question: "Who discovered the neutron?",
  a: "Niels Bohr",
  b: "Ernest Rutherford",
  c: "J.J. Thomson",
  d: "James Chadwick",
  co: "d",
},
{
  qn: 121,
  question: "What is the capital of the Netherlands?",
  a: "Rotterdam",
  b: "The Hague",
  c: "Amsterdam",
  d: "Utrecht",
  co: "c",
},
{
  qn: 122,
  question: "Who wrote 'The Grapes of Wrath'?",
  a: "Ernest Hemingway",
  b: "F. Scott Fitzgerald",
  c: "John Steinbeck",
  d: "William Faulkner",
  co: "c",
},
{
  qn: 123,
  question: "What is the largest island in the Caribbean?",
  a: "Cuba",
  b: "Hispaniola",
  c: "Jamaica",
  d: "Puerto Rico",
  co: "a",
},
{
  qn: 124,
  question: "Who discovered the proton?",
  a: "Niels Bohr",
  b: "Ernest Rutherford",
  c: "J.J. Thomson",
  d: "James Chadwick",
  co: "b",
},
{
  qn: 125,
  question: "What is the capital of Switzerland?",
  a: "Zurich",
  b: "Geneva",
  c: "Bern",
  d: "Basel",
  co: "c",
},
{
  qn: 126,
  question: "Who wrote 'Brave New World'?",
  a: "George Orwell",
  b: "Aldous Huxley",
  c: "Ray Bradbury",
  d: "J.R.R. Tolkien",
  co: "b",
},
{
  qn: 127,
  question: "What is the capital of South Korea?",
  a: "Seoul",
  b: "Tokyo",
  c: "Beijing",
  d: "Bangkok",
  co: "a",
},
{
  qn: 128,
  question: "Who wrote 'The Hobbit'?",
  a: "J.R.R. Tolkien",
  b: "C.S. Lewis",
  c: "George R.R. Martin",
  d: "J.K. Rowling",
  co: "a",
},
{
  qn: 129,
  question: "What is the chemical symbol for water?",
  a: "H2O",
  b: "O2",
  c: "CO2",
  d: "NaCl",
  co: "a",
},
{
  qn: 130,
  question: "Who was the first man in space?",
  a: "Neil Armstrong",
  b: "Yuri Gagarin",
  c: "Buzz Aldrin",
  d: "John Glenn",
  co: "b",
},
{
  qn: 131,
  question: "What is the capital of Mexico?",
  a: "Guadalajara",
  b: "Monterrey",
  c: "Mexico City",
  d: "Cancun",
  co: "c",
},
{
  qn: 132,
  question: "Who wrote 'The Picture of Dorian Gray'?",
  a: "Oscar Wilde",
  b: "Charles Dickens",
  c: "Mark Twain",
  d: "H.G. Wells",
  co: "a",
},
{
  qn: 133,
  question: "What is the largest country by area?",
  a: "Canada",
  b: "China",
  c: "United States",
  d: "Russia",
  co: "d",
},
{
  qn: 134,
  question: "Who discovered the law of gravity?",
  a: "Albert Einstein",
  b: "Isaac Newton",
  c: "Galileo Galilei",
  d: "Nikola Tesla",
  co: "b",
},
{
  qn: 135,
  question: "What is the capital of Spain?",
  a: "Barcelona",
  b: "Madrid",
  c: "Seville",
  d: "Valencia",
  co: "b",
},
{
  qn: 136,
  question: "Who wrote 'The Adventures of Tom Sawyer'?",
  a: "Mark Twain",
  b: "Ernest Hemingway",
  c: "F. Scott Fitzgerald",
  d: "John Steinbeck",
  co: "a",
},
{
  qn: 137,
  question: "What is the smallest ocean in the world?",
  a: "Atlantic Ocean",
  b: "Indian Ocean",
  c: "Arctic Ocean",
  d: "Southern Ocean",
  co: "c",
},
{
  qn: 138,
  question: "Who painted the Sistine Chapel ceiling?",
  a: "Leonardo da Vinci",
  b: "Michelangelo",
  c: "Raphael",
  d: "Donatello",
  co: "b",
},
{
  qn: 139,
  question: "What is the capital of China?",
  a: "Shanghai",
  b: "Beijing",
  c: "Hong Kong",
  d: "Guangzhou",
  co: "b",
},
{
  qn: 140,
  question: "Who wrote 'The Brothers Karamazov'?",
  a: "Leo Tolstoy",
  b: "Fyodor Dostoevsky",
  c: "Anton Chekhov",
  d: "Ivan Turgenev",
  co: "b",
},
{
  qn: 141,
  question: "What is the largest lake in the world?",
  a: "Lake Superior",
  b: "Lake Victoria",
  c: "Caspian Sea",
  d: "Lake Baikal",
  co: "c",
},
{
  qn: 142,
  question: "Who discovered the structure of DNA?",
  a: "James Watson and Francis Crick",
  b: "Marie Curie",
  c: "Gregor Mendel",
  d: "Rosalind Franklin",
  co: "a",
},
{
  qn: 143,
  question: "What is the capital of Greece?",
  a: "Athens",
  b: "Thessaloniki",
  c: "Patras",
  d: "Heraklion",
  co: "a",
},
{
  qn: 144,
  question: "Who wrote 'The Count of Monte Cristo'?",
  a: "Victor Hugo",
  b: "Alexandre Dumas",
  c: "Jules Verne",
  d: "Honoré de Balzac",
  co: "b",
},
{
  qn: 145,
  question: "What is the largest island in the Mediterranean Sea?",
  a: "Sicily",
  b: "Sardinia",
  c: "Cyprus",
  d: "Crete",
  co: "a",
},
{
  qn: 146,
  question: "Who developed the polio vaccine?",
  a: "Albert Sabin",
  b: "Louis Pasteur",
  c: "Jonas Salk",
  d: "Edward Jenner",
  co: "c",
},
{
  qn: 147,
  question: "What is the capital of Turkey?",
  a: "Istanbul",
  b: "Ankara",
  c: "Izmir",
  d: "Antalya",
  co: "b",
},
{
  qn: 148,
  question: "Who wrote 'The Old Man and the Sea'?",
  a: "Ernest Hemingway",
  b: "F. Scott Fitzgerald",
  c: "John Steinbeck",
  d: "William Faulkner",
  co: "a",
},
{
  qn: 149,
  question: "What is the largest desert in Africa?",
  a: "Kalahari Desert",
  b: "Sahara Desert",
  c: "Namib Desert",
  d: "Libyan Desert",
  co: "b",
},
{
  qn: 150,
  question: "Who discovered the electron?",
  a: "Niels Bohr",
  b: "Ernest Rutherford",
  c: "J.J. Thomson",
  d: "James Chadwick",
  co: "c",
},
{
  qn: 151,
  question: "What is the capital of Poland?",
  a: "Warsaw",
  b: "Krakow",
  c: "Gdansk",
  d: "Wroclaw",
  co: "a",
},
{
  qn: 152,
  question: "Who wrote 'The Jungle Book'?",
  a: "Rudyard Kipling",
  b: "Jules Verne",
  c: "H.G. Wells",
  d: "Mark Twain",
  co: "a",
},
{
  qn: 153,
  question: "What is the largest planet in our solar system?",
  a: "Earth",
  b: "Jupiter",
  c: "Saturn",
  d: "Mars",
  co: "b",
},
{
  qn: 154,
  question: "Who painted 'Starry Night'?",
  a: "Vincent van Gogh",
  b: "Pablo Picasso",
  c: "Claude Monet",
  d: "Leonardo da Vinci",
  co: "a",
},
{
  qn: 155,
  question: "What is the capital of Norway?",
  a: "Bergen",
  b: "Trondheim",
  c: "Oslo",
  d: "Stavanger",
  co: "c",
},
{
  qn: 156,
  question: "Who wrote 'The Catcher in the Rye'?",
  a: "J.D. Salinger",
  b: "Harper Lee",
  c: "F. Scott Fitzgerald",
  d: "John Steinbeck",
  co: "a",
},
{
  qn: 157,
  question: "What is the largest ocean on Earth?",
  a: "Atlantic Ocean",
  b: "Indian Ocean",
  c: "Arctic Ocean",
  d: "Pacific Ocean",
  co: "d",
},
{
  qn: 158,
  question: "Who discovered penicillin?",
  a: "Marie Curie",
  b: "Alexander Fleming",
  c: "Louis Pasteur",
  d: "Isaac Newton",
  co: "b",
},
{
  qn: 159,
  question: "What is the capital of Japan?",
  a: "Seoul",
  b: "Beijing",
  c: "Tokyo",
  d: "Bangkok",
  co: "c",
},
{
  qn: 160,
  question: "Who wrote '1984'?",
  a: "George Orwell",
  b: "Aldous Huxley",
  c: "Ray Bradbury",
  d: "J.R.R. Tolkien",
  co: "a",
},
{
  qn: 161,
  question: "What is the smallest country in the world?",
  a: "Monaco",
  b: "Vatican City",
  c: "San Marino",
  d: "Liechtenstein",
  co: "b",
},
{
  qn: 162,
  question: "Who painted the Mona Lisa?",
  a: "Vincent van Gogh",
  b: "Pablo Picasso",
  c: "Leonardo da Vinci",
  d: "Claude Monet",
  co: "c",
},
{
  qn: 163,
  question: "What is the longest river in the world?",
  a: "Amazon River",
  b: "Nile River",
  c: "Yangtze River",
  d: "Mississippi River",
  co: "b",
},
{
  qn: 164,
  question: "Who discovered penicillin?",
  a: "Marie Curie",
  b: "Alexander Fleming",
  c: "Louis Pasteur",
  d: "Isaac Newton",
  co: "b",
},
{
  qn: 165,
  question: "What is the hardest natural substance on Earth?",
  a: "Gold",
  b: "Iron",
  c: "Diamond",
  d: "Platinum",
  co: "c",
},
{
  qn: 166,
  question: "What is the largest ocean on Earth?",
  a: "Atlantic Ocean",
  b: "Indian Ocean",
  c: "Arctic Ocean",
  d: "Pacific Ocean",
  co: "d",
},
{
  qn: 167,
  question: "Who was the first person to walk on the moon?",
  a: "Buzz Aldrin",
  b: "Yuri Gagarin",
  c: "Neil Armstrong",
  d: "Michael Collins",
  co: "c",
},
{
  qn: 168,
  question: "What is the chemical symbol for gold?",
  a: "Au",
  b: "Ag",
  c: "Pb",
  d: "Fe",
  co: "a",
},
{
  qn: 169,
  question: "Who wrote '1984'?",
  a: "George Orwell",
  b: "Aldous Huxley",
  c: "Ray Bradbury",
  d: "J.R.R. Tolkien",
  co: "a",
},
{
  qn: 170,
  question: "What is the capital of Japan?",
  a: "Seoul",
  b: "Beijing",
  c: "Tokyo",
  d: "Bangkok",
  co: "c",
},
{
  qn: 171,
  question: "What is the largest desert in the world?",
  a: "Sahara Desert",
  b: "Gobi Desert",
  c: "Kalahari Desert",
  d: "Arctic Desert",
  co: "a",
},
{
  qn: 172,
  question: "Who developed the theory of relativity?",
  a: "Isaac Newton",
  b: "Albert Einstein",
  c: "Galileo Galilei",
  d: "Nikola Tesla",
  co: "b",
},
{
  qn: 173,
  question: "What is the capital of Australia?",
  a: "Sydney",
  b: "Melbourne",
  c: "Canberra",
  d: "Brisbane",
  co: "c",
},
{
  qn: 174,
  question: "Who is known as the 'Father of Computers'?",
  a: "Alan Turing",
  b: "Charles Babbage",
  c: "John von Neumann",
  d: "Bill Gates",
  co: "b",
},
{
  qn: 175,
  question: "What is the tallest mountain in the world?",
  a: "K2",
  b: "Kangchenjunga",
  c: "Mount Everest",
  d: "Lhotse",
  co: "c",
},
{
  qn: 176,
  question: "Who wrote 'Pride and Prejudice'?",
  a: "Jane Austen",
  b: "Charlotte Bronte",
  c: "Emily Bronte",
  d: "Mary Shelley",
  co: "a",
},
{
  qn: 177,
  question: "What is the capital of Canada?",
  a: "Toronto",
  b: "Vancouver",
  c: "Ottawa",
  d: "Montreal",
  co: "c",
},
{
  qn: 178,
  question: "Who invented the telephone?",
  a: "Alexander Graham Bell",
  b: "Thomas Edison",
  c: "Nikola Tesla",
  d: "Guglielmo Marconi",
  co: "a",
},
{
  qn: 179,
  question: "What is the largest mammal in the world?",
  a: "Elephant",
  b: "Blue Whale",
  c: "Giraffe",
  d: "Hippopotamus",
  co: "b",
},
{
  qn: 180,
  question: "What is the capital of Italy?",
  a: "Venice",
  b: "Milan",
  c: "Rome",
  d: "Florence",
  co: "c",
},
{
  qn: 181,
  question: "Who wrote 'The Odyssey'?",
  a: "Homer",
  b: "Virgil",
  c: "Sophocles",
  d: "Euripides",
  co: "a",
},
{
  qn: 182,
  question: "What is the smallest planet in our solar system?",
  a: "Mercury",
  b: "Venus",
  c: "Mars",
  d: "Pluto",
  co: "a",
},
{
  qn: 183,
  question: "Who discovered America?",
  a: "Christopher Columbus",
  b: "Ferdinand Magellan",
  c: "Vasco da Gama",
  d: "James Cook",
  co: "a",
},
{
  qn: 184,
  question: "What is the capital of Russia?",
  a: "Saint Petersburg",
  b: "Moscow",
  c: "Kiev",
  d: "Minsk",
  co: "b",
},
{
  qn: 185,
  question: "Who wrote 'The Great Gatsby'?",
  a: "Ernest Hemingway",
  b: "F. Scott Fitzgerald",
  c: "John Steinbeck",
  d: "William Faulkner",
  co: "b",
},
{
  qn: 186,
  question: "What is the largest continent?",
  a: "Africa",
  b: "Asia",
  c: "Europe",
  d: "North America",
  co: "b",
},
{
  qn: 187,
  question: "Who was the first President of the United States?",
  a: "Thomas Jefferson",
  b: "John Adams",
  c: "George Washington",
  d: "James Madison",
  co: "c",
},
{
  qn: 188,
  question: "What is the capital of Germany?",
  a: "Munich",
  b: "Frankfurt",
  c: "Berlin",
  d: "Hamburg",
  co: "c",
},
{
  qn: 189,
  question: "Who wrote 'Moby-Dick'?",
  a: "Herman Melville",
  b: "Nathaniel Hawthorne",
  c: "Edgar Allan Poe",
  d: "Mark Twain",
  co: "a",
},
{
  qn: 190,
  question: "What is the largest island in the world?",
  a: "Greenland",
  b: "New Guinea",
  c: "Borneo",
  d: "Madagascar",
  co: "a",
},
{
  qn: 191,
  question: "Who invented the light bulb?",
  a: "Nikola Tesla",
  b: "Alexander Graham Bell",
  c: "Thomas Edison",
  d: "George Westinghouse",
  co: "c",
},
{
  qn: 192,
  question: "What is the capital of India?",
  a: "Mumbai",
  b: "New Delhi",
  c: "Bangalore",
  d: "Kolkata",
  co: "b",
},
{
  qn: 193,
  question: "Who wrote 'War and Peace'?",
  a: "Fyodor Dostoevsky",
  b: "Leo Tolstoy",
  c: "Anton Chekhov",
  d: "Ivan Turgenev",
  co: "b",
},
{
  qn: 194,
  question: "What is the largest bone in the human body?",
  a: "Femur",
  b: "Humerus",
  c: "Tibia",
  d: "Fibula",
  co: "a",
},
{
  qn: 195,
  question: "Who was the first woman to win a Nobel Prize?",
  a: "Marie Curie",
  b: "Rosalind Franklin",
  c: "Dorothy Hodgkin",
  d: "Ada Lovelace",
  co: "a",
},
{
  qn: 196,
  question: "What is the capital of Brazil?",
  a: "Rio de Janeiro",
  b: "São Paulo",
  c: "Brasília",
  d: "Salvador",
  co: "c",
},
{
  qn: 197,
  question: "Who wrote 'The Catcher in the Rye'?",
  a: "J.D. Salinger",
  b: "Harper Lee",
  c: "F. Scott Fitzgerald",
  d: "John Steinbeck",
  co: "a",
},
{
  qn: 198,
  question: "What is the largest organ in the human body?",
  a: "Heart",
  b: "Liver",
  c: "Skin",
  d: "Lungs",
  co: "c",
},
{
  qn: 199,
  question: "Who was the first woman to fly solo across the Atlantic Ocean?",
  a: "Amelia Earhart",
  b: "Bessie Coleman",
  c: "Harriet Quimby",
  d: "Jacqueline Cochran",
  co: "a",
},
{
  qn: 200,
  question: "What is the capital of Egypt?",
  a: "Cairo",
  b: "Alexandria",
  c: "Giza",
  d: "Luxor",
  co: "a",
}
];
